libs/hc_metric/src/contributor_trust.rs, libs/hc_report_builder/src/lib.rs, xtask/src/main.rs
=> Get Hipcheck back to a "clean" build

.github/conventional-commits.yml
This commit adds Conventional Commit format checking to CI on PRs and pushes to the main branch.
=> feat: Add Conventional Commit check to CI

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, scripts/module-deps.js
This commit adds some basic "community" docs like a code of conduct and contributing file.
It also fixes the file extension for the license (it's not really markdown, so `.md` wasn't right), and adds a little explanation of the purpose of the helper script at the top just for clarity's sake.
=> chore: Added basic community docs.

SECURITY.md
Adds a security policy for Hipcheck.
=> chore: Adds security policy

docs/rfds/0002-hipcheck's-values.md
This commit adds a new RFD describing Hipcheck's product values and project values.
[__Rendered__](https://github.com/mitre/hipcheck/blob/25ff3b28ffa6ffb40ab5ebe935a8360f9a116c49/docs/rfds/0002-hipcheck's-values.md)
Closes #17
=> Add "Hipcheck's Values" RFD

Cargo.lock, hipcheck/Cargo.toml
=> Remove unused tempdir dependency

.github/workflows/website.yml
This is an experimental first-pass at a GitHub Action implementation for deploying the work-in-progress Hipcheck website.
=> chore: Add GitHub Action for site deployment.

site/content/docs/_index.md, site/content/docs/guide/why.md, site/content/docs/quickstart/_index.md, site/content/install/_index.md, site/templates/shortcodes/button.html
This fixes more broken links through pages beyond the index page. I believe with this that all internal links should now be good. I've tried to be much more consistent about using the proper internal linking syntax as well when I was writing the docs.
=> fix: Fix more broken links.

hipcheck/src/source/source.rs
Working directly with local repos presents a challenge for 3.5.0 feature #183 . This PR changes local repo handling to do a local `git clone` to `$HC_CACHE/clones/local`. The subdir created in this path is returned and is used for all future operations on the repository.
=> feat: local repos are also cloned to HC_CACHE

Cargo.lock, hipcheck/Cargo.toml, hipcheck/src/analysis/score.rs, hipcheck/src/benchmarking.rs, hipcheck/src/cli.rs, hipcheck/src/main.rs, hipcheck/src/session/session.rs, hipcheck/src/shell.rs, hipcheck/src/shell/color_choice.rs, hipcheck/src/shell/iter.rs, hipcheck/src/shell/macros.rs, hipcheck/src/shell/par_iter.rs, hipcheck/src/shell/prelude.rs, hipcheck/src/shell/progress_phase.rs, hipcheck/src/shell/spinner_phase.rs, hipcheck/src/shell/verbosity.rs, hipcheck/src/source/source.rs
This PR contains an early but hopefully mostly functional draft of the new hipcheck shell. 
This is marked as a draft because there are almost certainly bugs that I haven't gotten around to fixing yet, but it should be in a state where people can start finding them and contributing commits to fix them or letting me know about them. Once enough of the bugs are cleared, we can merge this, and then have other pull requests to start converting various phases and analyses to use the new `SpinnerPhase` and `ProgressPhase` structs. 
This includes all the changes from #195, which I'm assuming will get merged before this.
=> feat: Shell rework

hipcheck/src/cli.rs, hipcheck/src/main.rs, hipcheck/src/session/session.rs, hipcheck/src/shell.rs, hipcheck/src/shell/iter.rs, hipcheck/src/shell/progress_phase.rs, hipcheck/src/target.rs, hipcheck/src/target/types.rs
This pulls in the shell/session/etc tweaks that are in https://github.com/mitre/hipcheck/pull/212 without pulling in the `git2`-based source clone/pull code.
=> chore: Variety of tweaks to the shell and phase infrastructure.

site/content/install/_index.md
=> fix: Add missing step to install instructions

hipcheck/src/session/session.rs
=> feat: make conf-not-found error message suggest use of `hc setup`

site/content/rfds/0003-plugin-architecture-vision.md, site/content/rfds/0004-plugin-api.md
Closes #11.
Edit: **[__Rendered__](https://github.com/mitre/hipcheck/blob/416530d6e496d7c9a0ef756c7ec32292063bd529/site/content/rfds/0004-plugin-api.md)**
=> RFD #4: Plugin API

hipcheck/src/config.rs, hipcheck/src/metric/affiliation.rs, hipcheck/src/metric/binary_detector/query.rs, hipcheck/src/metric/linguist/query.rs, hipcheck/src/metric/typo.rs, hipcheck/src/policy/policy_file.rs
Adds code that allows config file locations provided in a policy file to be read into Salsa in `config.rs`
=> fix: Adds code to retrieve config information from policy file analyses.

hipcheck/src/config.rs, hipcheck/src/policy/mod.rs, hipcheck/src/policy/policy_file.rs
This lets us get configuration for a specific analysis by name, with a little bit of recursive searching.
=> feat: Added PolicyFile::get_config method

hipcheck/src/config.rs, hipcheck/src/policy/policy_file.rs, hipcheck/src/report/mod.rs, hipcheck/src/report/report_builder.rs
Update salsa functions and ReportBuilder to determine overall pass/fail based on policy expression
=> feat: update report to use investigate policy expression

config/Hipcheck.kdl, hipcheck/src/analysis/result.rs, hipcheck/src/analysis/score.rs, hipcheck/src/config.rs, hipcheck/src/engine.rs, hipcheck/src/plugin/mod.rs, hipcheck/src/plugin/types.rs, hipcheck/src/report/mod.rs, hipcheck/src/report/report_builder.rs, hipcheck/src/shell/mod.rs
This commit completes the minimum viable product of the plugin system by adding support for reporting the results of running plugins.
=> feat: Add support for reporting plugin results.

.github/workflows/dockerhub.yml, Containerfile
The Containerfile was using an outdated version of Rust that was causing compilation failures. This bumps it to the latest.
=> chore: Update Containerfile

Cargo.lock, Cargo.toml, hipcheck/src/main.rs, plugins/dummy_sha256_sdk/Cargo.toml, plugins/dummy_sha256_sdk/schema/query_schema_sha256.json, plugins/dummy_sha256_sdk/src/main.rs
This branch implements the `dummy/sha256` plugin with the `hipcheck-sdk`
This will close #423
=> feat: dummy sha256 plugin using hipcheck-sdk

site/content/rfds/0005-target-resolution-refactor.md, site/content/rfds/0007-simplified-release-procedures.md
Currently in a very rough draft format. Just wanted to get the ideas down before pivoting to working on the plugin system.
Resolves #262 .
=> Add RFD #5: Target Resolution Refactor

Cargo.lock, Cargo.toml, plugins/npm_dependencies/Cargo.toml, plugins/npm_dependencies/src/main.rs, plugins/npm_dependencies/src/npm.rs, plugins/npm_dependencies/src/util/command.rs, plugins/npm_dependencies/src/util/fs.rs, plugins/npm_dependencies/src/util/mod.rs
Resolves issue #480 
This is mainly a refactor of extant code from `hipcheck/src/data/{mod.rs, npm.rs , and queries::dependencies.rs}`.
=> feat(refactor): Created a plugin version of the NPM dependency query

sdk/rust/src/plugin_engine.rs
=> fix: PluginEngine::query not using inner function broadly enough

config/Hipcheck.kdl, hipcheck/src/policy/config_to_policy.rs, hipcheck/src/policy/mod.rs, hipcheck/src/policy/policy_file.rs, hipcheck/src/policy/test_example.kdl, hipcheck/src/policy/tests.rs
=> feat: add `patch` field to policy file to allow config of dependent plugins

hipcheck/src/source/git.rs
Resolves #580 
If the `git2` crate would error when trying to find a given refspec using the `revparse_single("1.2.3")` method, now we try that same method again as `revparse_single("v1.2.3")` to cover the case of repos that use that style of version tagging. If the method errors both times, then we return an error with some extra information.
=> fix: Tries refspec with leading "v" if it fails without one

hipcheck/src/cache/repo.rs
The `cache delete` subcommand had a bug in how it was sorting entries to be deleted or preserved, so that `-s all` would actually choose to keep all instead of delete all entries. Also updated the per-entry deletion logic to also clean up the parent dir (corresponding to github owner) if it was made empty by deleting the child dir.
=> fix: `hc cache` deletion logic

hipcheck/src/main.rs, hipcheck/src/session/mod.rs
=> chore: remove hc_github_token from hipcheck core

hipcheck/src/cli.rs, hipcheck/src/config.rs, hipcheck/src/policy/config_to_policy.rs, hipcheck/src/policy/test_example.kdl
config --> policy file conversion and test files needed updates to match changes to per-plugin config/version expectations
=> fix: update config to policy file conversion and associated tests

dist/Containerfile
=> fix: update `hc` bin location in containerfile

hipcheck/src/policy/macros.rs, site/content/docs/guide/config/policy-file.md
=> feat: add #env macro to policy file parsing

.github/ISSUE_TEMPLATE/release_todo_tracker.md
=> feat: add issue template for tracking version bumps ahead of release

sdk/rust/src/engine.rs
- added convenience function for instantiating a `QueryBuilder` to dynamically buildup a query and send to a target plugin endpoint
- completed RFD 0009 implementation
=> feat: added "batch" function to PluginEngine in rust SDK

site/config.toml, site/templates/bases/base.tera.html, site/templates/index.html, site/templates/macros/breadcrumbs.tera.html, site/templates/partials/footer.tera.html, site/templates/partials/install.tera.html, site/templates/partials/nav.tera.html
This commit improves the styling of the site navigation to make it clearer and easier to scan through, and also updates the styling of the home page for similar reasons.
=> feat: Improve desktop site nav and home.

hipcheck/src/cli.rs, hipcheck/src/main.rs, hipcheck/src/session/mod.rs
Resolves #582
Resolves #682
Hipcheck now defaults to using a policy file called `Hipcheck.kdl` in the default config dir.
It will fall back to loading the legacy TOML format if that fails.
If the user explicitly calls for `--policy` or `--config`, Hipcheck will only attempt that source of configuration, not falling back to the other.
Add a new `Provenance` enum for tracking whether a setting was set explicitly by a user or is from defaults.
Add a new `ConfigMode` enum to make fewer invalid states representable.
=> feat: Default to policy file at standard location (#582, #682)

hipcheck/src/cache/plugin.rs
Implemented the delete function.
=> feat: implemented delete

.github/workflows/release.yml, dist-workspace.toml, hipcheck/dist.toml, sdk/rust/src/lib.rs
=> Pre-release fixes for 3.10.0

site/content/docs/guide/making-plugins/_index.md, site/content/docs/guide/making-plugins/query-protocol.md, site/content/docs/guide/making-plugins/release.md
=> chore(docs): add description of the Query protocol

hipcheck/src/exec.rs
Resolves #913 
Added `cfg!` macro to set default `backoff_interval` to appropriate value for MacOS, and cleaned up the exec.rs file.
=> feat: make Exec.kdl defaults os-aware

dist/Containerfile, site/config.toml, site/content/blog/2025-02-21-hipcheck-3.11.0-release.md, site/static/dl/install.ps1, site/static/dl/install.sh
I may want to find some more varied emojis.
=> chore: release announcement and site changes for 3.11

hipcheck/src/cache/plugin.rs, hipcheck/src/cli.rs, hipcheck/src/main.rs
CLI interface should just be CLI.
=> feat: first version of listing and deleting plugins with CLI 

hipcheck/dist.toml, plugins/activity/dist.toml, plugins/affiliation/dist.toml, plugins/binary/dist.toml, plugins/churn/dist.toml, plugins/entropy/dist.toml, plugins/fuzz/dist.toml, plugins/git/dist.toml, plugins/github/dist.toml, plugins/identity/dist.toml, plugins/linguist/dist.toml, plugins/npm/dist.toml, plugins/review/dist.toml, plugins/typo/dist.toml
=> chore: add mold to ubuntu target in dist.toml for all dist targets

site/templates/bases/base.tera.html, site/templates/index.html, site/templates/partials/footer.tera.html, site/templates/partials/nav.tera.html
Padding added to the base section and footer. Unsure is header should be padded to so left that as is
=> Fix x-padding on website index page.

Cargo.lock, hipcheck/Cargo.toml, hipcheck/src/session/mod.rs, hipcheck/src/target/mod.rs, hipcheck/src/target/multi.rs, hipcheck/src/target/resolve.rs, hipcheck/src/target/types.rs, library/hipcheck-workspace-hack/Cargo.toml
Ugly code that we will refactor, but added some basic go.mod file parsing and made the associated async / stream changes that fell out from that. I want to commit this for establishing how TargetSeed into Target resolution streaming should work.
=> feat: basic go.mod parsing and async refactor

hipcheck/src/plugin/retrieval.rs, hipcheck/src/target/multi.rs, library/hipcheck-common/src/chunk.rs
Update the logic in `multi.rs` to do more correct go module resolution following the official Go docs.
=> feat: add proper go.mod dependency resolution

.github/workflows/website-test.yml, Cargo.lock, sdk/python/docs/source/index.rst, sdk/rust/Cargo.toml, sdk/rust/README.md, site/config.toml
Resolves #1082 .
Resolves #1111 .
=> py-site-fixes

hipcheck/src/cli.rs, hipcheck/src/main.rs, site/content/docs/guide/cli/_index.md, site/content/docs/guide/cli/hc-explain.md, site/content/docs/guide/cli/hc-setup.md
=> Updates to CLI documentation

hipcheck/src/main.rs
=> fix: Handle possible error in creating new default tokio runtime

Cargo.lock, hipcheck/Cargo.toml, library/hipcheck-common/Cargo.toml, library/hipcheck-sdk-macros/Cargo.toml, plugins/activity/Cargo.toml, plugins/affiliation/Cargo.toml, plugins/binary/Cargo.toml, plugins/churn/Cargo.toml, plugins/entropy/Cargo.toml, plugins/fuzz/Cargo.toml, plugins/git/Cargo.toml, plugins/github/Cargo.toml, plugins/identity/Cargo.toml, plugins/linguist/Cargo.toml, plugins/npm/Cargo.toml, plugins/review/Cargo.toml, plugins/typo/Cargo.toml, sdk/rust/Cargo.toml
Please approve but do not merge yet :)
=> chore: bump crate versions ahead of 3.13 release

hipcheck/src/cli.rs, hipcheck/src/explain/mod.rs, hipcheck/src/explain/semver.rs, hipcheck/src/main.rs, hipcheck/src/plugin/mod.rs, hipcheck/src/plugin/plugin_manifest.rs
=> Add `hc explain semver` subcommand to explain version requirements

plugins/activity/plugin.kdl, plugins/affiliation/plugin.kdl, plugins/binary/plugin.kdl, plugins/churn/plugin.kdl, plugins/entropy/plugin.kdl, plugins/fuzz/plugin.kdl, plugins/git/plugin.kdl, plugins/github/plugin.kdl, plugins/identity/plugin.kdl, plugins/linguist/plugin.kdl, plugins/npm/plugin.kdl, plugins/review/plugin.kdl, plugins/typo/plugin.kdl
An oversight in the prior version-bump commit.
=> fix: Bump plugin versions in plugin manifests

.github/workflows/commits.yml, .github/workflows/docker.yml, .github/workflows/dockerhub.yml, .github/workflows/hipcheck.yml, .github/workflows/website-deploy.yml, .github/workflows/website-test.yml, .github/zizmor.yml
This applies some security improvements to our GitHub Actions based on recommendations from zizmor. It does not fully address all Zizmor findings, but should be a good start.
=> Harden GitHub Actions
