.github/dependabot.yml

Let Dependabot open Pull Requests when Hipcheck dependencies are out of date. Hopefully this will help us stay on top of new versions over time.

feat: Enable dependabot version bumps

---

Cargo.lock
libs/hc_shell/Cargo.toml
libs/hc_shell/src/lib.rs

This commit removes `atty` as a dependency. The Rust standard library
provides the same functionality built in now, and `atty` has a known
low-severity vulnerability and is unmaintained.
Signed-off-by: Andrew Lilley Brinker <abrinker@mitre.org>

fix: Remove 'atty' dep for GHSA-g98v-hv3f-hcfr

---

hipcheck/src/data/github/authenticated_agent.rs
hipcheck/src/data/github/hidden.rs

This commit adds SPDX license notice comments to the top of two source files that were missing it. These were identified with the `cargo xtask validate` command.

Add missing license notices.

---

.cargo/config.toml
xtask/src/main.rs

This commit fixes a runtime error that was stopping `cargo xtask` from running at all. Basically, we define a custom `--version` command, which was conflicting with the one automatically generated by `clap`, resulting in a runtime failure.
This command just adds a line telling `clap` not to generate its own `version` flag, resolving the error and allowing `xtask` to run as expected.

Fix double-version command in `xtask`

---

hipcheck/src/data.rs
hipcheck/src/data/es_lint/mod.rs
hipcheck/src/data/git/mod.rs
hipcheck/src/data/query/mod.rs
hipcheck/src/error.rs
hipcheck/src/filesystem.rs
hipcheck/src/main.rs
hipcheck/src/report.rs
hipcheck/src/shell.rs
hipcheck/src/test_util.rs

This commit removes all "#[allow(unused)]` annotations and all the dead code that removal of those annotations revealed. This is code that isn't used today and which we don't expect to use in the future, though of course it exists in the project history so we can get it back if we really need to.

Removed dead code.

---

docs/rfds/0001-release-engineering.md

This commit adds a "Release Engineering" RFD which proposes both how the workflow should run for publication of new Hipcheck versions, as well as changes to Hipcheck itself to support the new workflow.
__[Rendered](https://github.com/mitre/hipcheck/blob/4cdc6d3358fe4640a80a96a4f7b59ce108580bda/docs/rfds/0001-release-engineering.md)__

Added "Release Engineering" RFD

---

.github/workflows/release.yml
Cargo.toml
hipcheck/Cargo.toml

This commit is just the result of getting 'cargo dist init' running, and
sets up the basics for distributing Hipcheck to end users with pre-built
binaries. Note that currently the installation after the binary is set
up will still be missing additional files Hipcheck needs, as well as its
broader dependencies, so this isn't a sufficient installation setup on
its own.
Signed-off-by: Andrew Lilley Brinker <abrinker@mitre.org>

feat: Add 'cargo-dist' for prebuilt binaries.

---

.github/workflows/release.yml
Cargo.toml

This commit does three things:
- Updates to the latest version of `cargo-dist`
- Expands the set of targets we build for.
- (Should) fix building for `musl` targets by making sure we have OpenSSL dev files installed to support static linking.

fix: Fix broken `cargo-dist` build.

---

Cargo.lock
hipcheck/Cargo.toml

This commit does two things:
- Improves the `Cargo.toml` metadata.
- Removes some unused dependencies.
For the first item, the improvements are:
- Added keywords.
- Added categories.
- Fixes include path for the `LICENSE` file.
For the second item, the improvements are:
- Removed `curl`
- Removed `glob`
- Removed `criterion` (dev-dependency)
- Removed `duct` (dev-dependency)

Improved `Cargo.toml` metadata, removed unused deps.

---

.cargo/config.toml
.gitignore
Cargo.lock
Cargo.toml
xtask/Cargo.toml
xtask/src/main.rs
xtask/src/task/changelog.rs
xtask/src/task/check.rs
xtask/src/task/ci.rs
xtask/src/task/mod.rs
xtask/src/workspace.rs

This commit introduces a new `xtask changelog` command to `cargo xtask`, to help produce automated changelogs which can be the basis for updating `CHANGELOG.md`. This new command _does not_ overwrite `CHANGELOG.md`, but instead writes its auto-generated changelog to `CHANGELOG-NEXT.md`, which is also marked in `.gitignore` so it doesn't get checked in. The goal here is that this automation will _help_ write changelogs for each new version, but doesn't turn the changelog into a fully-automated system, as we still want to be able to have human-written release notes.

add `xtask changelog` command.

---

.github/workflows/test.yml

Filter GitHub workflow to not run tests if changes to a push or pull-request are outside of code folders `config`, `hipcheck`, `scripts`, or `xtask`.

chore: Do not run tests if changes outside code folders

---

Containerfile

When we combined all of Hipcheck's crates into a single binary crate, we did away with the need for a `/libs` folder. The `Container` file was never updated to no longer try to copy the contents of this folder during the Docker installation procedure. This removes that unnecessary and `docker build` breaking copy from the `Container` file.

fix: Removes missing /libs folder from Container file

---

Cargo.lock
Cargo.toml
Containerfile
docs/rfds/0001-release-engineering.md
hipcheck/Cargo.toml
hipcheck/src/analysis/session/pm.rs
hipcheck/src/data/github/authenticated_agent.rs

Removes OpenSSL as a necessary Hipcheck dependency. Accomplishes this by switching the [ureq](https://crates.io/crates/ureq) https client's TLS implementation from [native-tls](https://crates.io/crates/native-tls) (which uses OpenSSL on Linux platforms) to [rustls](https://crates.io/crates/rustls).
Updates the documentation and Docker Containerfile updated to reflect Hipcheck not needing a separate OpenSSL installation.

Chore: Remove OpenSSL as a Hipcheck dependency

---

xtask/src/task/ci.rs

Resolves Issue #86  Fixes the `xtask ci` task to correctly call `xtask check` instead of the deprecated `xtask validate`.

fix: Change xtask validate to xtask check when xtask ci is called.

---

.github/workflows/test.yml
Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/cli.rs
hipcheck/src/main.rs

This changes the CLI for the `hc` command to use `clap`'s "derive" syntax over the previous "build" syntax. This makes the CLI run at compile-time, which will save time when Hipcheck is run on different data sources without recompilation in between (as we expect) with typical use.
As a bonus feature, the CLI no longer panics if no command argument is provided. Instead it displays the appropriate help text, as expected.

chore (cli): Changes hc CLI to use compile-time "derive" syntax

---

hipcheck/src/cli.rs
hipcheck/src/main.rs

Adds the `hc ready` command. This checks that:
- git and NPM are installed and sufficiently up to date, and if installed prints their versions
- The home directory, config file, and data directory can all be found, and if set prints their respective locations
- The HC_GITHUB_TOKEN environment variable is set (but it does not check that the token is valid)
If git and NPM are up to date and home, config, and data are all found, the command reports that Hipcheck is ready to run. Otherwise it reports that Hipcheck is not ready.

feat: Adds hc ready command

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/data/github/authenticated_agent.rs

Use the `rustls-native-certs` crate to have `rustls` use the user's native system certs instead of the Mozilla root certs when constructing a `ureq` authentication agent. This is the only place Hipcheck needs these certs, so it is now configured to use system certs with TLS.

chore(http): Change `ureq` Agent to use native system certs

---

xtask/src/task/rfd.rs

Resolves issue #87   Adds the missing license and description to the file xtask/src/task/rfd.rs

chore: Add license and description to rfd.rs

---

xtask/src/task/changelog.rs

close #88. 
If git-cliff is not installed, `cargo xtask changelog` will now exit and print `[ERROR] changelog requires ``git-cliff`` to be installed. Please install it with ``cargo install git-cliff`` ` (double backticks appear as single backticks in practice).

fix: add xtask changelog sanity check for git cliff

---

hipcheck/src/cli.rs
hipcheck/src/main.rs

This MR resolves #105  and #106 issues pertaining to the replacement of unhelpful error msgs that Hipcheck emits when either `check` or `schema` subcommands are invoked without any arguments. 
This is addressed simply by updating the type of the `command` field in the `CheckArgs` and `SchemaArgs` structs from an `Option` to just the underlying type. This conveys to `clap` that **some** subcommand must be parsed from the remaining arguments for things to move forward - if this does not happen, it will print the `-h` help msg. 
The `match` statements associated with these `command` fields in `main.rs` are updated in accordance with this change.

feat(cli): hc check and schema will print help msg when no subcommand

---

.github/workflows/push-to-docker.yml

Resolves #22.
Repo has been updated with secrets for `DOCKER_USERNAME` and `DOCKER_TOKEN`.
Being a github action, this is difficult to test without publishing a new release or manually triggering by modifying the `on` field of the action's `.yml` file. 
In theory we should be able to manually trigger from GitHub once this is merged into `main`

Publish tagged HC releases on Dockerhub in MITRE namespace

---

hipcheck/src/analysis/session/mod.rs
hipcheck/src/config.rs

Resolves #108 .
Function `resolve_config()` is no longer called in `load_config_and_data()`, and used to return a path with `Hipcheck.toml` at the end, necessitating a call to `.parent()` to get the conf dir to pass to `Config::load_from()`. With the new CLI, the path doesn't have `Hipcheck.toml` on the end, but the `.parent()` call was left accidentally.
This fix removes the unneeded call, and adds a check to `Config::load_from()` that the passed path is not a regular file to provide users with a clearer error message if they accidentally set `HC_CONFIG` to point to `Hipcheck.toml`.

fix mishandling of `HC_CONFIG` with new CLI

---

.github/workflows/push-to-docker.yml

As discussed in HC weekly meeting, add ability to manually trigger `push-to-docker.yml` job, particularly useful in case there are bugs in the script that get discovered the first time a new version gets cut.

feat: add ability to manually exec push-to-dockerhub action

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/analysis.rs
hipcheck/src/analysis/analysis.rs
hipcheck/src/analysis/report_builder.rs
hipcheck/src/analysis/result.rs
hipcheck/src/analysis/score.rs
hipcheck/src/data/es_lint/data.rs
hipcheck/src/data/modules.rs
hipcheck/src/main.rs

**Note**: Not sure why the Ubuntu `clippy` is complaining about unused fields now that it used to not have a problem with. Perhaps a change was made over the past few days that removed `Debug` from the field usage calculation?
An attempt at defining new types for overhauling the `AnalysisResult` system and Hipcheck scoring in general. `HC` prefix was added to structs/variants to disambiguate with existing structs and can/should be renamed once the old system has been removed in a subsequent PR.
The goal of this PR is to produce an `AnalysisReport` replacement with the following changes:
- Analysis implementations no longer check `db.<X>_active()` to decide themselves whether or not to run. The old `AnalysisOutcome` enum contains the `Skip` variant which is absent from the new one. …

refactor: added new types to form the basis of scoring refactor

---

Cargo.toml

As part of changing our installation flow, we want to have an `hc setup` command which installs the required configuration and support scripts for Hipcheck. To do this, we're updating our `cargo-dist` configuration to make sure those files are bundled with the release bundles made with each Hipcheck release.

chore: Make `cargo-dist` releases include `config/` and `scripts/`

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/metric/typo.rs
hipcheck/src/test_util.rs

Some of our dependencies still use it so it's not entirely out of the project, but after these changes we will no longer depend on it directly.
Resolves #143

Remove dependency on lazy_static.

---

hipcheck/src/metric/entropy.rs

This is #134, but reworked to be onto `main` instead of `venus/performance`, and to not have the many merge conflicts that branch had on both `venus/performance` and `main`.

feat: Parallelize grapheme collection across files.

---

hipcheck/src/cli.rs
hipcheck/src/main.rs
hipcheck/src/session/session.rs
hipcheck/src/target.rs

Resolves issue #95 
Removes all code that  "patch" as an option for `hc check` and `hc schema`, as Hipcheck currently does not support patches as a type to check.
Also removes the "unsupported type" and "not a valid type" error options for target types in the places they appear, as those would now be unreachable code blocks.

chore: Removes patch type as option

---

hipcheck/src/analysis/analysis.rs
hipcheck/src/analysis/report_builder.rs
hipcheck/src/analysis/result.rs
hipcheck/src/analysis/score.rs

(new copy of PR #132 rebased off of main)
Continuation of effort on #28.
This adds affiliation to the set of analyses using the new scoring/storage system, but the main contribution of this PR is the run_and_score_threshold_analysis macro defined in score.rs. If approved, this will make converting the rest of the analyses much simpler and reduce lines of (committed) code. The macro is a bit in-elegant but we expect churn in this area of Hipcheck in the next few months anyway, I doubt this will remain for very long.
It might also be worthwhile to add a similar macro for analyses on the new system in analysis/report_builder.rs.

chore: refactor affiliation analysis, experiment with macro

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/cli.rs
hipcheck/src/main.rs
hipcheck/src/setup.rs

Resolves #103.
This PR adds the `hc setup` CLI command for finishing the installation of an `hc` binary. This primarily includes:
-  acquiring target locations for the `HC_CONFIG, HC_DATA` directories. 
- creating those directories if they don't exist
- finding a suitable local copy of a `cargo-dist` release bundle for Hipcheck
- this could be a dir, zip, or tar.xz file
- if none is found, one will be automatically downloaded from our Hipcheck release page on github
- decompressing the source bundle if applicable, and copying the contents of the source `config/, scripts/` dirs to `HC_CONFIG, HC_DATA`, respectively.
- cleaning up any downloaded files or uncompressed directories created in service of the above operations
The cmdline is `hc setup [--offline] [SOURCE]`. If `--offline` …

Add `hc setup` installation command

---

hipcheck/src/analysis/analysis.rs
hipcheck/src/analysis/report_builder.rs
hipcheck/src/analysis/result.rs
hipcheck/src/analysis/score.rs

Continuation of effort on #28 .
This PR applies the refactor demonstrated in #132 to all repo analyses (PR analyses will be removed in a subsequent commit following @alilleybrinker 's guidance).
The number of lines changed seems daunting, but its really just the same pattern:
- Update analysis function and storage to return and store `HCAnalysisReport` and `HCStoredResult`, respectively
- Update analysis function content to not check for `db.X_active()`, and just return the calculated value instead of checking own threshold and scoring by itself
- Remove analysis type from `score.rs::phase_outcome()`
- Change analysis execution in `score.rs::score_results()` to use new macro
- Change processing of results for analysis in `report_builder.rs`
Of the above, ensuring that the analysis …

chore: refactor all remaining repo analyses

---

hipcheck/src/cli.rs

This is intended to make it a little bit clearer to use, specifically by converting the positional argument into a flag, and by adding more explanatory text.

feat: Slightly modified arguments for `hc setup`.

---

hipcheck/src/analysis/report_builder.rs
hipcheck/src/analysis/score.rs

Continuation of effort on #28 .
Previous PRs on this front have introduced an alternative `ScoringResults` obj called `AltScoringResults`, which stores results in a hashmap instead of as fields of a compile-time object, which will help enable the plugin system going forward.
This PR does the work of fully replacing any usage of `ScoringResults` with the hash-map alternative, which has been renamed to `ScoringResults` as the old one is purged from the codebase.

chore: replace prior AnalysisResults obj with AltAnalysisResults impl

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/analysis/report_builder.rs
hipcheck/src/analysis/score.rs
hipcheck/src/config.rs
hipcheck/src/session/session.rs

Continuation of effort on #28 .
This PR introduces the "weight tree" - a tree structure containing the normalized weights of each analysis according to the config. Presently, the structure of the weight tree (i.e. which analyses fall under which parent nodes) is hard-coded to match the existing analysis hierarchy, but in the future plugin system the abstraction of getting a weight tree from salsa can allow us to produce differently-shaped trees.
The weight tree can be combined with the hashmap-style `AnalysisResults` objects that previous PR #159 made the de facto storage location for analysis results. This function `synthesize()` produces an `AltScoreTree` (to be renamed upon becoming the de facto scoring tool). As the code walks the `WeightTree`, it uses the analysis label to index the …

feat: add weight tree and replace old scoring

---

xtask/src/main.rs
xtask/src/task/site/serve.rs

This adds a new `--env` flag to the `xtask site serve` subcommand that lets you specify if you're wanting to run in production or development mode. The only thing this changes at the moment is the `base_url` of the site, intended so you can locally test the production configuration of the deployment. By default, it'll use `--env dev`, which sets the `base_url` to `localhost`.

feat: Added `--env` flag to `xtask site serve`

---

site/templates/macros/breadcrumbs.tera.html
site/templates/partials/footer.tera.html
site/templates/partials/nav.tera.html

This fix _should_ correct broken links throughout the site when deployed into production by making sure they're properly prefixed based on the `base_url`.

fix: Correct broken links throughout the site.

---

hipcheck/src/analysis/score.rs
hipcheck/src/cli.rs
hipcheck/src/main.rs
hipcheck/src/shell.rs

Provide CLI functionality to print the resolved weights used in analysis. 
Closes #28

Weight Tree Printing

---

site/content/docs/_index.md
site/content/docs/quickstart/_index.md
site/content/install/_index.md
site/content/rfds/0000-rfds.md
site/content/rfds/_index.md
site/templates/bases/base.tera.html
site/templates/shortcodes/button.html

This commit completes the installation instructions with additional content describing how to use Hipcheck from a container.
It also includes a complete Quickstart guide to Hipcheck, plus some other small utility pieces including some CSS fixes and a new "button" shortcode.

feat: Completed the install instructions and Quickstart guide.

---

Cargo.lock
hipcheck/src/cli.rs
hipcheck/src/main.rs

Resolves issue #56  Adds `hc update` command to run the self-updater (if installed). This updater comes with the current Hipcheck installer as created by `cargo-dist` using the `axoupdater` crate. The `hc-update` command simply calls the `axoupdater` provided updater, but integrated into the regular Hipcheck CLI. 
This command automatically brings Hipcheck up to date with the latest released version if run without any flags. The user can includes optional flags to update to versions other than the latest.
N.B. Because of a bug in `cargo-dist`, we cannot be sure if the `axoupdater` updater will be installed as `hc-update` or `hipcheck-update`. Therefore the new `hc update` command tries both commands. If this bug is resolved in the future, we can remove the step of checking both possible …

feat: Adds hc update command

---

.github/workflows/release.yml
Cargo.toml

Changes the version of `cargo-dist` used by Hipcheck to version 0.17.0. Makes changes in `release.yml` to make it compatible with that version.

chore: Update cargo-dist to version 0.17.0

---

Containerfile

Resolves #104
Also fix the reference to the `.target` directory in the Containerfile; This path was changed back to the default in 5790939a.
Since the Debian default shell when building the Containerfile doesn't support `-o pipefail`, remove that option from the `set` commands.

build: Use Debian base image instead of Alpine (#104)

---

Containerfile

In an attempt to minimize container layer sizes, this deletes the apt cache.

build: Clean apt cache after installation

---

site/config.toml
site/templates/index.html
site/templates/partials/footer.tera.html
site/templates/partials/nav.tera.html

Previously, by hardcoding a number of links, we were breaking in production because the production site is served under a sub-path of the `https://mitre.github.io` host: `hipcheck/`. This commit fixes many of these broken links, including those on the homepage and in the navigation and footer, as I now better understand Zola's mechanism for linking to pages within the site in a way that always ensures proper handling of the site's `base_url`.

fix: Fix broken website links in production.

---

.github/workflows/release.yml
Cargo.toml

Update `cargo-dist` to v0.18.0-prerelease1, which fixes TLS issues related to system certs.

chore (deps): Update cargo-dist to v0.18.0-prerelease1

---

.github/workflows/test.yml

Relates to #139
The `rust-cache` action will preserve the CARGO_HOME and target directories between builds. These contain the downloaded dependency crates (in source code) and the compiled dependency crates, respectively.
Key the cache on the OS target to keep the caches separate between OS builds.
Docs:
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
https://github.com/Swatinem/rust-cache
https://github.com/axodotdev/cargo-dist/issues/907

build: Use rust-cache in GitHub CI to speed up builds

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/cli.rs
hipcheck/src/target.rs

Resolves issue #184 .
`hc check` will now attempt to resolve the target type from a given target pURL. Currently we support GitHub, Maven, NPM, and PyPi pURL's. If a target type can be resolved, Hipcheck will extract the information it needs to run from the pURL.
If the user provides a target type to `hc check` with the `-t` flag, Hipcheck will error if the inferred type (whether inferred from a pURL, GitHub URL, or .spdx file extension) does not match the provided type.

feat(CLI): CLI can infer target type from target pURL

---

hipcheck/src/cli.rs
hipcheck/src/target.rs
hipcheck/src/target/types.rs

Adds new types, including `Target` which is designed to replace `Source` going forward. Future work will integrate this type into the Hipcheck analysis, and derive `Target` from `CheckArgs`
Additionally adds the optional `ref_` arg to `CheckRepoArgs` and fixes `trailing_args` to also consume flag arguments. Without this, `--ref` can't be passed when not using deprecated `hc check repo/maven/etc <TARGET>` format.

feat: added types for new target repo spec and resolution

---

Cargo.lock
hipcheck/src/cli.rs
hipcheck/src/main.rs
hipcheck/src/session/pm.rs
hipcheck/src/session/session.rs
hipcheck/src/source.rs
hipcheck/src/source/query.rs
hipcheck/src/source/source.rs
hipcheck/src/target.rs
hipcheck/src/target/types.rs

The need for the refactor represented by this PR was determined from discussions around tackling #183 .
This PR was a collaborative effort between myself and @mchernicoff .
This PR uses the types defined in `target/types.rs` for representing the "target" of a HipCheck analysis. Although information can be specified on the cmdline by users in a variety of ways (variants of `TargetSeed`), we eventually need to arrive at a local clone of a git repository that may or may not have an associated remote repo / package information. This is all encapsulated by the `Target` struct.
This PR provides glue code for converting `cli.rs` structures to `TargetSeed` instances using the `ToTargetSeed` trait. The `resolve_target()` function does the work of `TargetSeed` to `Result<Target>` translation. 
In …

feat: add more robust 'target resolution' system

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/log_bridge.rs
hipcheck/src/main.rs
hipcheck/src/shell.rs

`indicatif-log-bridge` was improperly filtering log messages in some instances, and was pretty easy to replace.

chore: Replace log bridge dependency with bespoke implementation

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/cache.rs
hipcheck/src/cli.rs
hipcheck/src/main.rs
hipcheck/src/metric/typo.rs

This PR contributes to #182 . 
It introduces the `hc cache` command which allows controlled listing/deleting of cache entries (rooted in the `HC_CACHE` path resolved by the standard CLI).
**This PR does not currently take measures to short-cut dir-size calculation, so each operation can take multiple seconds to complete.** It should be discussed whether this is important enough to require before this PR is merged or can be addressed subsequently. 
`cli.rs` - changes to introduce the subcommand.
`main.rs` - call `cmd_cache()` function when CLI dictates
`cache.rs` - supporting types and the `HcCache` object itself, with public-facing functions for listing/deleting entries.

feat: add `hc cache` subcommand for manually listing/deleting elements of the cache

---

hipcheck/src/cache.rs
hipcheck/src/main.rs

This PR introduces a filesystem backing for the `HcCache` object, stored at `$HC_CACHE/clones/index.json`. When instantiating a `HcCache` object, the constructor now looks for this file, and if it exists, will compare `last_modified` information to shortcut cache entry size calculation if the entry has not been modified since the last time a cache object was instantiated. 
Landing this will help with the potential feature described in #182 , where we may specify a cache size-reduction policy to run every time `hc check` or other subcommands are run. Without this shortcutting, re-calculating the disk size of each cache entry can add significant time overhead, impacting user experience with the tool.
Notably, the way this PR determines index entry invalidation is currently based on if the …

feat: shortcut cache entry size calculation with cache index file

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/cli.rs
hipcheck/src/session.rs
hipcheck/src/session/cyclone_dx.rs
hipcheck/src/session/pm.rs
hipcheck/src/session/session.rs
hipcheck/src/session/spdx.rs
hipcheck/src/session/tests/juiceshop_bom.json
hipcheck/src/target.rs
hipcheck/src/target/types.rs

Partially resolves Issue #186  Hipcheck can now process SBOMs using both SPDX and CycloneDX (currently JSON only) standard. Currently we only support CycloneDX JSONs in versions 1.3 - 1.5 of the CycloneDX specification.

feat: Hipcheck can process SBOMs using CycloneDX JSONs

---

hipcheck/src/cli.rs
hipcheck/src/session/pm.rs
hipcheck/src/target.rs

Resolves Issue #235. Hipcheck will now include the scope for scoped NPM packages in the format `@scope/package@version`.
This works with NPM targets in `package@version`, NPM registry URL, or pURL formats.

fix: Hipcheck now works with scoped npm packages.

---

hipcheck/src/cli.rs
hipcheck/src/main.rs
hipcheck/src/session/session.rs
hipcheck/src/source/git.rs
hipcheck/src/source/source.rs
hipcheck/src/target/types.rs

This PR splits `source/git.rs::update()` into `fetch()`, and `checkout()`. It also updates the `TargetSeed::RemoteRepo` variant to pass along `--ref` info from the cmdline to the new `checkout()` function.
The desire for `--ref` exposes some limitations of the current `TargetSeed` enum. Data passed on the CLI through `--ref` can easily be slotted into `LocalGitRepo`, but not into the other variants. One option would be to break away from using `Target` subfields for each variant so the wrapped structs can carry more information. I opted instead to just add another field to the variant, but the decision is very much up for discussion.
Note that this PR does not address passing `--ref` info for other `TargetSeed` variants.

feat: update remote-repo updating to support git refs

---

hipcheck/src/cache.rs

Following discussion in team channel, clean up language about the importance of calling `drop` on an HcCache instance.

fix: correct language in the description of HcCache::drop

---

hipcheck/src/cli.rs
hipcheck/src/main.rs
hipcheck/src/session/pm.rs
hipcheck/src/session/session.rs
hipcheck/src/target/types.rs

Following a team discussion, this PR renames the existing `TargetSeed` enum to `TargetSeedKind` and wraps it with a new `TargetSeed` struct that allows `refspec` info to be passed from the CLI for non-local repos. 
This PR does not introduce git ref support for packages or SBOMs, it simply refactors the existing logic.

chore(refactor): distinguish TargetSeed and TargetSeedKind

---

hipcheck/src/cli.rs
hipcheck/src/session/session.rs
hipcheck/src/source/git.rs
hipcheck/src/source/source.rs
hipcheck/src/target/types.rs

We do not seem to currently harvest version information from SBOMs and Maven URLs. In the future we will need to add `--ref` vs. harvested-version resolution strategies to them like has been done here for `TargetSeedKind::Package`.

feat: add --ref support to remaining target seed kinds

---

hipcheck/src/cache.rs

Found this bug while working on other stuff, the `CacheDeleteScope::All` handling doesn't apply the passed filter, so `hc cache delete -p hipcheck` will still try to delete all entries in the cache instead of only those matching the pattern.

fix: hc cache now applies pattern to `all` target

---

Containerfile

The containerfile used for 3.4.0 and 3.5.0 was quietly broken and deploys to Docker Hub were failing. This commit _should_ fix the brokenness based on local testing. The file has also been shortened, removing comments which were not needed or no longer accurate. Commands in the `RUN` directive are also now joined by `&&` instead of `;` to ensure early termination if an error arises.

Fix broken containerfile.

---

.github/workflows/push-to-docker.yml
dist/dockerhub/README.md

I added a new folder to the top level of the repo `third-party-docs` and added `README-dockerhub.md` file with a README that can be added to `mitre/hipcheck` page on dockerhub. I am not sure if we want to make another top-level directory, but I did not want to clutter the root of the repository with something that is only for Dockerhub. If anyone has suggested alternatives, please let me know!
I could not find any information for adding/editing the description via any official Docker tooling, but I found this [link](https://github.com/peter-evans/dockerhub-description) if we want to add this to CI to be run after deploying the latest image to Dockerhub
As far as adding tags, there did not seem to be an automated way of doing it. This …

docs: added README for dockerhub

---

.github/workflows/commits.yml
.github/workflows/dockerhub.yml
.github/workflows/hipcheck.yml
.github/workflows/website-deploy.yml
.github/workflows/website-test.yml

This commit features several CI improvements:
- Clearer naming of CI files, pipelines, and jobs.
- Adds "website-test.yml" to test website changes on PRs.
- Removes duplicative tests on `main` after equivalent tests on PRs, given that PRs can only merge with passing tests.

CI improvements

---

.github/workflows/hipcheck.yml
Cargo.lock
Containerfile
hipcheck/Cargo.toml
hipcheck/build.rs
hipcheck/proto/hipcheck.proto
hipcheck/src/.gitignore
hipcheck/src/main.rs
site/content/install/_index.md

Initial commit to inject `hipcheck.proto` --> `hipcheck.rs` code gen into our build process. Updated site install instructions, GitHub CI, and Containerfile to include `protoc` install. 
Windows `protoc` install for GitHub CI is currently reliant on curling specific version, which will need to be updated over time. Assuming `chocolatey` is installed, could use [this package](https://community.chocolatey.org/packages/protoc) instead. Site shows a few warnings about binaries included, so I was hesitant.

feat: add proto-file based code gen

---

.github/workflows/hipcheck.yml

Pull Request #264 changed the build settings so that tests would not be run on all pushes to the `main` branch.
Unfortunately, while it seems wasteful to do redundant builds, this has the consequence of preventing re-use of build caches.
The reason is that build caches created for Pull Requests are isolated from other PRs (except those based on that PR) and the `main` branch. Build caches created for `main` _can_ be re-used in PR builds, which is what we want.
[GitHub Actions docs on re-use of build caches](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache)
The good news is that this should save build time overall. It should also reduce churn in the storage of caches: Most of …

fix(build): Always run tests on main to create reusable caches

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/plugin/download_manifest.rs
hipcheck/src/plugin/mod.rs

Implemented the logic for parsing download manifest files in rfd4:
https://github.com/mitre/hipcheck/blob/main/site/content/rfds/0004-plugin-api.md

feat: added parsing logic for download manifests

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/plugin/manager.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/types.rs

**Note**: This PR relies on #278 which must be merged first.
This PR makes small adjustments to and expands upon #278 . The `PluginExecutor` now has a `start_plugins()` async function which allows a set of plugins to be started concurrently. For a simple implementation, this required removing mutable state from the `PluginExecutor`, hence the elimination of the `est_ports` field.
The `HcPluginCore` struct was added, which is intended to manage the protocol state of connections to each plugin and handle requesting info from a different plugin on behalf of another. The `HcPluginCore::new()` function takes an executor, and a set of `(Plugin, Configuration)` pairs. This function starts all the plugins and also initializes them over gRPC by getting the schemas, setting the config, and getting …

Plugin initialization and aggregation

---

.github/workflows/release.yml
Cargo.toml

Resolves #280  Updates `cargo-dist` to version 0.21.0. Makes necessary changes to cargo dist's config in the `Cargo.toml` file.

chore: Update cargo-dist to 0.21.0

---

hipcheck/src/cli.rs
hipcheck/src/main.rs
hipcheck/src/session/session.rs

Resolves Issue #292 .Adds new `-p`/`--policy` flag to pass a policy file to Hipcheck. Defaults to a file named `Hipcheck.KDL` in the current working directory if the flag is omitted.
`hc ready` now checks for a policy file. If one is missing, a custom error message reminds the user to provide one manually.
Currently, instead of erroring if *no* policy file is provided, Hipcheck errors *if* a file is provided, as policy files are not currently supported by Hipcheck. This will change in a future PR once downstream parsing of policy files has been implemented.

feat (cli): Adds new --policy flag to Hipcheck

---

Cargo.lock
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/types.rs

*Note* This PR relies on #290 . Merge this only after it has been merged.
This PR further wraps `PluginTransport` in an `ActivePlugin` struct, which manages query "sessions". It is responsible for handing out query IDs to new queries (`next_id` is guarded by a Mutex), and converts `Query --> PluginResponse` object which either returns the result or packages the info needed to "resume" the current query once the required information has been gathered.
This also implements multiplexing on the `PuginTransport::rx` receiver, along with a backlog of messages. This way a query session can ignore but save messages not destined for them.
Overall, this PR also accomplishes removing `&mut` references from the plugin communication interface so it can be `Send` and thus eligible for salsa async …

feat: plugin interface handles multiple active query sessions

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/main.rs
hipcheck/src/policy_exprs/bridge.rs
hipcheck/src/policy_exprs/env.rs
hipcheck/src/policy_exprs/error.rs
hipcheck/src/policy_exprs/expr.rs
hipcheck/src/policy_exprs/mod.rs
hipcheck/src/policy_exprs/token.rs

This is still a work-in-progress, and nothing is actually used yet, but this at least moves over the draft implementation of policy expressions from the external experimental repo I'd made to enable integration with Hipcheck.
The other thing I did was organize the Cargo.toml file for the hipcheck crate, particularly to put all dependencies in alphabetical order, as they had been at one point previously.
Resolves #260

Integrate policy expressions code

---

hipcheck/src/engine.rs
hipcheck/src/main.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/types.rs

**Note**: This relies on PR #297 . Merge that one first.
This PR integrates the plugin querying infrastructure that has been built up by previous PRs into the salsa Database framework. The `HcEngine` trait and `HcEngineImpl` struct expose a (synchronous) `query(publisher, plugin, name, key)` interface, which accesses a global `tokio` runtime to call the `async fn`s for invoking `HcPluginCore` functionality. The `query` function is recursive, so the "stack" of query state is represented by actual stack frames.

plugin Salsa integration

---

hipcheck/src/cli.rs
hipcheck/src/session/session.rs
hipcheck/src/shell.rs
hipcheck/src/shell/spinner_phase.rs
hipcheck/src/source/git.rs

When running `hc check --format json -v quiet https://github.com/mitre/hipcheck`, the following error occurs on `origin/main`
Here is the tip of `origin/main` with the policy file error omitted
The tip of this branch has nothing printed before the JSON is output
If anyone has an idea of how to test this/ensure I hid everything that should be hidden when `-v quiet` is passed, I would love to hear it!

fix quiet bug regression

---

Cargo.lock
hipcheck/src/engine.rs
hipcheck/src/main.rs
plugins/dummy_rand_data/Cargo.toml
plugins/dummy_rand_data/src/hipcheck_transport.rs
plugins/dummy_rand_data/src/main.rs

This PR updates the `dummy_rand_data` plugin binary to support multiple active queries (mostly mirroring what was done for `hipcheck/plugin` in #297 ) .
Key changes:
`engine.rs` - added `async_query`, an async version of the salsa memoized `query()` function. This does not memoize, its just a proof of concept that we would be able to perform recursive calls to an async function.
`main.rs` - updates `cmd_plugin()` to actually spawn multiple simultaneously queries (using `async_query`, with a commented-out version demonstrating how to do so with sync `query()`)
`hipcheck_transport.rs` - does receiver multiplexing
`main.rs` - `RandDataRunner` now spawns off a task that handles the individual query, giving it a cloned version of the HcTransport object for communicating over the gRPC channel.

feat: update dummy plugin to handle concurrent queries

---

hipcheck/Cargo.toml

Without this included, the `build.rs` won't get published to Crates.ip, which would be a problem.

chore: Include `build.rs` in `hipcheck` crate

---

hipcheck/src/cache/plugin_cache.rs
hipcheck/src/plugin/download_manifest.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/plugin_manifest.rs
hipcheck/src/plugin/supported_arch.rs

Updated `arch` fields in the download and plugin manifest structs to hold an enum of the architectures supported by hipcheck

chore: now store architecture as an enum

---

.gitignore
Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/analysis/score.rs
hipcheck/src/config.rs
hipcheck/src/engine.rs
hipcheck/src/metric/affiliation.rs
hipcheck/src/metric/churn.rs
hipcheck/src/metric/entropy.rs
hipcheck/src/metric/identity.rs
hipcheck/src/metric/review.rs
hipcheck/src/metric/typo.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/types.rs
hipcheck/src/policy_exprs/mod.rs
hipcheck/src/session/mod.rs
hipcheck/src/target/types.rs

A roughly implemented PR that changes `score_results()` to use the plugin query infrastructure to drive analysis. Does not yet make use of `PolicyExpr` for scoring purposes. `AnalysisTree` ought to be the main object for driving execution/scoring going forward.

feat: introduce plugin-based query infrastructure to scoring

---

Cargo.toml

Turns out we'd forgotten to update the cargo-dist configuration to install the protobuf compiler for our release builds in CI. This commit _should_ fix it, though I'm not able to test it until it's deployed and I try to cut a new release.
The basic idea here is that cargo-dist provides configuration items to use platform-specific package managers to install needed packages. In our case, funnily enough, the protobuf compiler package has a different name on every platform.
For the moment I am not tying us to a specific version, just using the `*` to indicate we should always be using latest. If that becomes an issue in the future we can tighten it up.

fix: Install the protobuf compiler in release CI

---

Containerfile

Builds for Docker images to publish to Docker Hub were failing because we weren't copying in all the crates found in the top-level workspace `Cargo.toml` file, causing Cargo to complain. This fixes that by copying them into the builder, though they don't get built.

fix: Copy plugins into containerfile build step

---

hipcheck/src/kdl_helper.rs
hipcheck/src/main.rs
hipcheck/src/plugin/download_manifest.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/plugin_manifest.rs
hipcheck/src/policy/mod.rs
hipcheck/src/policy/policy_file.rs
hipcheck/src/policy/tests.rs
hipcheck/src/policy_exprs/mod.rs
hipcheck/src/session/mod.rs

Partially resolves #329 
Adds data structures and functions to parse a policy file in KDL format.
The parsed policy file is currently not used by Hipcheck, and Hipcheck still needs a Config.toml file to run.

feat: Adds structures and functions to parse policy files.

---

hipcheck/src/policy/policy_file.rs
hipcheck/src/policy/tests.rs

Adds the missing `weight` field to the `PolicyCategory` struct. This field represents optional weights that can be given to categories of analyses in the policy file and was accidentally omitted in the PR that added that struct.

fix: Adds weight field to policy file categories

---

.github/workflows/docker.yml
.github/workflows/hipcheck.yml
.github/workflows/release-dry-run.yml

This commit adds three new categories of CI jobs:
- Weekly Docker image build testing
- Weekly release dry run testing (not currently including `cargo-dist`)
- Simplifications to regular testing, including installing `protoc` with Chocolatey on Windows, and using `cargo-nextest` for testing, along with validating `cargo xtask check` in CI now.

chore: More CI jobs

---

hipcheck/src/config.rs
hipcheck/src/policy/config_to_policy.rs
hipcheck/src/policy/mod.rs
hipcheck/src/policy/test_example.kdl
hipcheck/src/policy/tests.rs
hipcheck/src/session/mod.rs

Resolves issue #335 
If no KDL policy file is given by the user, but a deprecated TOML config file is found, Hipcheck will convert the config file to a policy file structure before running.
Note that this forces certain default choices on Hipcheck, because the older config file format does not contain all the same information a policy file.

chore: Converts config file to policy file under the hood

---

hipcheck/src/policy_exprs/error.rs
hipcheck/src/policy_exprs/json_pointer.rs
hipcheck/src/policy_exprs/mod.rs
site/content/rfds/0004-plugin-api.md

Resolves #261
This PR adds a JSON Pointer preprocessor step before parsing and evaluation of Policy Expressions.
It adds a `context` parameter to the execution of Policy Expressions, which is used to lookup values referred to by the JSON Pointers.
It allows a limited subset of the full JSON Pointer syntax: only alphanumeric, '/' (slash), '~' (tilde), and '_' (underscore) characters are allowed.
This PR also adds a `MultipleErrors` variant of `policy_exprs::error::Error`. It is probably not the best long term design to solve the problem of tracking a list of errors found during parsing, checking, and execution of a language.

feat: Add JSON Pointer preprocessor for Policy Expression language

---

hipcheck/src/config.rs
hipcheck/src/policy/config_to_policy.rs
hipcheck/src/policy/test_example.kdl
hipcheck/src/policy/tests.rs

PR #315 implemented JSON Pointer syntax, and it uses slashes instead of the dotted syntax originally used in the RFD.
This PR updates the hardcoded policy expressions to use the new syntax.
Also fix syntax for literal `true` value (`#t`).

fix: Update hardcoded policy expressions with new JSON pointer syntax

---

hipcheck/src/config.rs
hipcheck/src/metric/commit_trust.rs
hipcheck/src/metric/contributor_trust.rs
hipcheck/src/policy/mod.rs
hipcheck/src/policy/policy_file.rs

Change the legacy salsa functions that provide analysis-specific configuration to extract from policy file.

chore: update legacy config salsa funcs to use policy file get_config()

---

hipcheck/src/analysis/mod.rs
hipcheck/src/analysis/score.rs

Changed all legacy analyses save for those that rely on special configs to return `Result<QueryResult>`.
Notable side effects:
- Can't return Error that also has concerns
- Lose the ability to flag concerning commits since the way we decide whether they are concerning is in the policy expression

chore: change legacy analyses to return QueryResult

---

hipcheck/src/cli.rs
hipcheck/src/main.rs
hipcheck/src/session/mod.rs

Resolves #335  Makes the `--config` flag a deprecated flag, so that it will not appear under in the `hc` executable's help text. Adds various warning and error messages to the user explaining that a policy file is preferred over a config file.
Swaps the `-c`  and `-C' short flags between the now deprecated `--config` and the still support `--cache` flags.

chore (CLI): Deprecates the config arg

---

config/Hipcheck.kdl
hipcheck/src/analysis/mod.rs
hipcheck/src/analysis/score.rs
hipcheck/src/cache/plugin_cache.rs
hipcheck/src/config.rs
hipcheck/src/engine.rs
hipcheck/src/plugin/download_manifest.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/plugin_id.rs
hipcheck/src/plugin/plugin_manifest.rs
hipcheck/src/plugin/retrieval.rs
hipcheck/src/plugin/supported_arch.rs
hipcheck/src/plugin/types.rs
hipcheck/src/policy/config_to_policy.rs
hipcheck/src/policy/policy_file.rs
hipcheck/src/policy/tests.rs
hipcheck/src/session/mod.rs
hipcheck/src/util/fs.rs
site/content/rfds/0004-plugin-api.md

This pull request does the following:
- adds example `Hipcheck.kdl` to `config/`
- download and extract specified plugins (excluding legacy mitre/* plugins)
- updated RFD 4 to indicate `plugin.kdl` is the expected name of the plugin manifest for a plugin
- added SUPPORTED_ARCH constant that can be used to determine what rust triple version is currently running, used to determine which version of plugins to download and which entrypoints to use

feat: plugin downloading and extraction added to `hc check`

---

hipcheck/src/engine.rs
hipcheck/src/main.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/types.rs
plugins/dummy_rand_data/src/main.rs

update `HcEngine` interface queries to use proper plugin key
update `hc plugin` dummy plugins to have `dummy` publisher

fix: make HcEngine plugin lookup use {publisher}/{plugin} as key

---

hipcheck/src/analysis/score.rs

There was a `panic` call in some scoring code that meant we would panic if we hit an error evaluating a policy expression instead of returning it nicely. This converts that error into a nicer one.

fix: Remove scoring panic.

---

.github/workflows/mac-build-custom-setup.yml
.github/workflows/release.yml
Cargo.toml

We hit a bug in 'cargo-dist' yesterday that it turns out was already fixed in the latest version, but before we figured that out we implemented a workaround to enable us to get 3.6.2 out the door. Now that we know the latest 'cargo-dist' version doesn't need the workaround, we can revert it and use 0.22.1.

chore: Revert 'cargo-dist' workaround

---

config/Hipcheck.kdl
hipcheck/src/policy/config_to_policy.rs
hipcheck/src/policy/test_example.kdl
hipcheck/src/policy_exprs/env.rs
hipcheck/src/policy_exprs/mod.rs
hipcheck/src/report/report_builder.rs

Fixed some policies used in the legacy config file conversion. To be able to express legacy churn pass/fail computation in policy expressions, needed to add a `divz` function, which will divide two ints/floats or return 0 if the divisor is 0.

feat: add divz policy-expr func and fix some policies in legacy config file conversion

---

Containerfile

I believe this is the issue that prevented `3.6.*` images from publishing to Dockerhub, but I have not yet tested building the image locally. I am updating my VM to ubuntu 22.04, and then I will attempt to build with `podman`, but I have been have certificate issues building it locally with `docker`
I also noticed that https://github.com/mitre/hipcheck/actions/runs/10764246899 failed 2 days ago and went unnoticed. Maybe we could figure out a way to have an issue be added to the backlog if that pipeline fails, or maybe building the docker image on each commit would be better?

fix: fix issue building Docker image

---

site/config.toml

The website is pointing to `3.5.0` not `3.6.3` (latest)

fix: hipcheck site now pointing to 3.6.3 (latest)

---

hipcheck/src/data/es_lint/data.rs
hipcheck/src/data/es_lint/mod.rs
hipcheck/src/main.rs
hipcheck/src/plugin/download_manifest.rs
hipcheck/src/plugin/manager.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/plugin_manifest.rs
hipcheck/src/session/pm.rs
hipcheck/src/source/mod.rs

We have a lot of dead code left over from prior work, especially from the transition to the plugin system. This commit is the start of removing a lot of that dead code while ensuring everything still compiles and tests still pass.

chore: Removing dead code

---

README.md

Closes #64 
The existing public release statement included reference to the two contract numbers used for prior work on Hipcheck, done _before_ the public release event. This commit adds the number for the current contract.

chore: Add HSSEDI contract number to the README.

---

hipcheck/src/policy_exprs/expr.rs
hipcheck/src/policy_exprs/mod.rs

Idea is that `value: Option` will hold `None` until we are ready to evaluate.

feat: add placeholder for JSON pointer late-binding in policy expr

---

hipcheck/src/policy_exprs/token.rs

Relates to #371
This change is the initial step towards integrating JSON Pointers as a native part of the Policy Expression language.
This should have no visible effect on the behavior of Hipcheck yet, as it's not possible for the lexer to read JSON Pointer syntax after the preprocessor strips them out.

feat: Lex JSON Pointers in Policy Expressions

---

hipcheck/src/policy_exprs/expr.rs
hipcheck/src/policy_exprs/mod.rs

The existing parsing code requires that the top level expression is always a function call. I'm not sure if this is intentional or an oversight, but the evaluation code seems to have no problem evaluating other expressions at the top level.
This change allows any expression type at all in the parser.
This will enable testing policy expressions with a plain `#t` or `#f` to force success or failure, as well as permit a JSON Pointer at the top level.

feat: Allow any `Expr` at the top level of a Policy Expression

---

site/templates/partials/footer.tera.html

Closes #376
The site is served by GitHub Pages, which has a privacy policy that controls what data they collect when people browse to GitHub Pages sites, and how that data is used. This updates our site to now link to this policy in the footer on each page.

chore: Add GitHub privacy policy to website footer

---

.devcontainer/devcontainer.json

This commit does two things:
- Removes `module-deps` as an NPM dependency, since we no longer need/use it.
- Adds `protobuf-compiler` as an Apt dependency, since we need it to build our gRPC server definition.

chore: Update devcontainer definition

---

.buf.yaml
xtask/src/main.rs
xtask/src/task/buf.rs
xtask/src/task/mod.rs

This subcommand checks that you have the tool `buf` installed, and then uses it to lint against our protobuf definition files. This is intended to make it easier to lint these definitions in the future.

feat(xtask): Added 'buf' xtask subcommand

---

xtask/src/task/buf.rs
xtask/src/task/rfd.rs

Previously when making a new RFD, the `xtask` command would generate one without a YAML frontmatter, which would cause compilation with `zola` to fail. This fixes that, now including a YAML frontmatter with a `title` field filled with the title the user provided on the CLI.
Closes #425.

feat: Make `xtask rfd new` include title in RFD file

---

dist/Containerfile

It turns out the prior version of the `Containerfile` was broken, as the install script for Hipcheck wouldn't actually work due to a missing `xz-utils` package. This was obscured by my own networking issues, causing me to inadequately test the prior change.
One other change this makes is that it splits the `RUN` commands up with a `USER` command, so the first `RUN` is done as root to set up the system, and the second `RUN` is done as `hc_user` to install Hipcheck.

fix: Fix broken `Containerfile`

---

hipcheck/src/cli.rs
hipcheck/src/engine.rs
hipcheck/src/main.rs
hipcheck/src/plugin/download_manifest.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/supported_arch.rs

Resolves #415 .
We had previously encountered problems with cross-compilation to niche-but-valid architectures, where the compile-time target detection would fail, causing `CURRENT_ARCH` to be `()` instead of a valid arch enum variant. We changed this field to be type `Option<SupportedArch>` and also support a user-provided `--arch` flag to override the detected arch at runtime if the user has good reason to do so.

feat: add --arch flag to `hc check` subcommand to allow detection override

---

hipcheck/build.rs
hipcheck/src/cli.rs
hipcheck/src/engine.rs
hipcheck/src/main.rs
hipcheck/src/plugin/arch.rs
hipcheck/src/plugin/download_manifest.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/plugin_manifest.rs

This replaces `SupportedArch` with an `Arch` enum, which is further subdivided into `Unknown(String)` and the `KnownArch` enum.
Currently `DETECTED_ARCH` is `Option<KnownArch>`, but we could expand it to be just `Arch`, and try to get the target triple at compile time as a string to fill the `Arch::Unknown` variant. Without doing this, right now you'll be forced to specify `--arch` on the command line even if you build and run on the same arch, assuming its not one of the `KnownArch` types.

feat: allow use of unknown arches through commandline

---

plugins/dummy_rand_data_sdk/src/main.rs
sdk/rust/src/error.rs
sdk/rust/src/lib.rs
sdk/rust/src/plugin_engine.rs
sdk/rust/src/plugin_server.rs

Added and expanded API doc comments, renamed a couple of SDK `Error` enum variants for clarity.

chore: extend API doc comments for Rust SDK

---

hipcheck/src/policy_exprs/env.rs
hipcheck/src/policy_exprs/error.rs
hipcheck/src/policy_exprs/expr.rs
hipcheck/src/policy_exprs/token.rs

Resolves #401 
Adds comparison and basic arithmetic operators for `DateTime` and `Span` policy expression primitives.
To handle comparing `Spans` without erroring or needing to provide a datetime for each span, `Spans` must now not include years or months as units. `Spans` may include weeks as units, even though `jiff` normally has issues with comparing raw `Spans` with weeks, because we convert all weeks to seven 24-hour days during parsing.

feat: Adds operators for datetime and span policy expression primitives

---

hipcheck/src/engine.rs
hipcheck/src/policy_exprs/env.rs
hipcheck/src/policy_exprs/expr.rs
hipcheck/src/policy_exprs/mod.rs

Resolves #449 .
Pernicious bug in policy expression code. JSON has only "Number" type, doesn't distinguish between float and int. When a float that ends in `.0` gets serialized then injected into a policy expression, it is treated as an integer. Our policy expression evaluation logic for arithmetic/comparison requires operands be `int + int` or `float + float`, so when this bug occurs we get a type error because we do `int + float`. 
This fix updates `binary_primitive_op` to detect when the operands are `int+float` or `float+int` and implicitly upcasts the `int` to a `float`. It also removes other type checking from `binary_primitive_op`, as it was bad design. For example, although we updated `fn add` to allow `DateTime + Span`, the type checking in `binary_primitive_op` did not allow …

fix: policy expr type errors due to X.0 floating points in JSON being treated as ints

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/target/types.rs
sdk/rust/schema/hipcheck_target_schema.json

Resolves #444 .
Add a `.json` file to the Rust SDK crate folder so that developers of top-level plugins that receive serialized `Target`s can see what they look like. 
This doesn't do anything like make the contents of the JSON file available as a const string in the SDK so it can be accessed programatically, maybe that's something to consider doing.

chore: add hipcheck::target::Target schema to Rust SDK

---

sdk/rust/schema/hipcheck_target_schema.json

Resolves #453 .
In the Issue, I suggested that we would need to switch our use of `schemars::SchemaObject` to `RootSchema`, because just emitting the `schema_for!(Target).schema` for `Target` results in a definition with `#ref`s to objects that are not included in the document. 
I couldn't find a way through `schemars` native to emit a `SchemaObject` from a RootSchema with all the refs replaces with the definitions themselves, so I manually edited the resulting `.json` file. I ensured that deserializing this to a `schemars::SchemaObject` still works.

fix: update target json desc from RootSchema to SchemaObject

---

Cargo.lock
Cargo.toml
hipcheck-sdk-macros/Cargo.toml
hipcheck-sdk-macros/src/lib.rs
plugins/dummy_sha256_sdk/Cargo.toml
plugins/dummy_sha256_sdk/src/main.rs
sdk/rust/Cargo.toml
sdk/rust/src/error.rs
sdk/rust/src/lib.rs

Adds a Hipcheck SDK proc-macro that can mark functions to have a struct `impl Query` created.

feat: Adds query sdk proc-macro

---

hipcheck/src/policy_exprs/env.rs
hipcheck/src/policy_exprs/expr.rs
hipcheck/src/policy_exprs/token.rs
site/content/rfds/0004-plugin-api.md

Adds information about using `DateTime` and `Span` plugin primitives and their operations to RFD4. Changes some internal documentation and testing to be more explicit about what kinds of `Spans` are allowed.

chore (doc): Adds date and time information to Plugin RFD

---

Cargo.lock
Cargo.toml
plugins/github_api/Cargo.toml
plugins/github_api/src/code_search.rs
plugins/github_api/src/data.rs
plugins/github_api/src/gh_query.graphql
plugins/github_api/src/gh_schema.graphql
plugins/github_api/src/graphql.rs
plugins/github_api/src/main.rs
plugins/github_api/src/types.rs
plugins/github_api/src/util/agent.rs
plugins/github_api/src/util/authenticated_agent.rs
plugins/github_api/src/util/mod.rs
plugins/github_api/src/util/redacted.rs

Resolves #474 .
I plan to continue @patrickjcasey 's work next to make it easier to test these API endpoints.
Aside from the content of `main.rs`, this is mostly just copying extant code from `hipcheck/src/data/{mod.rs, github::*}`

feat(refactor): created plugin version of github api queries

---

plugins/dummy_rand_data_sdk/Cargo.toml
plugins/dummy_rand_data_sdk/schema/query_schema_get_rand.json
plugins/dummy_rand_data_sdk/src/main.rs
sdk/rust/Cargo.toml
sdk/rust/src/lib.rs
sdk/rust/src/mock.rs
sdk/rust/src/plugin_engine.rs

Resolves #431 .
Adds a feature flag to the Rust SDK called `"mock_engine"` that gates `PluginEngine` functionality and some imports. 
Adds a field to the `PluginEngine` called `mock_responses` that contains a lookup table. When `query()` is called, if the `"mock_engine"` feature is enabled, it will use that table instead of querying out to the Hipcheck core. This allows us to test query logic without spinning up a whole Hipcheck analysis. 
The SDK version of the `rand_data` plugin is updated to use the SDK macro system, and a test case has been added to demonstrate how plugins can be tested locally with `mock_responses`.
The `cfg` compiler flags have been carefully applied to ensure no "unused" warnings whether running with `"mock_engine"` or not.
I've temporarily left the commits split …

feat: add "mock_engine" feature to SDK to allow offline query testing

---

Cargo.lock
Cargo.toml
plugins/git/Cargo.toml
plugins/git/src/data.rs
plugins/git/src/main.rs
plugins/git/src/parse.rs
plugins/git/src/util/command.rs
plugins/git/src/util/git_command.rs
plugins/git/src/util/mod.rs

Resolves issue #472 
This is mainly a refactor of extant code from `hipcheck/src/data/{mod.rs, git::*}`. The Salsa queries have been changed to query functions compatible with the Hipcheck plugin query system.
We have not refactored data structures and functions related to commit signers, as no Hipcheck analysis currently uses those. These can be added in a future update if desired.
Note that queries involving datetimes accept and return datetime values as plain Strings in the correct formatting for `jiff::Timestamp.` Other plugins should parse and display datetimes accordingly when using the functions in this plugin.

feat(refactor): Created plugin version of git queries

---

hipcheck/src/policy_exprs/env.rs
hipcheck/src/policy_exprs/expr.rs
hipcheck/src/policy_exprs/json_pointer.rs
hipcheck/src/policy_exprs/mod.rs
hipcheck/src/policy_exprs/pass.rs

Resolves #457 .
This is also a portion of the proposed changes in #456 RFD8 .
1. Updates some `Expr` variants to have their own proper structs so we can have `visit_X` patterns on them
2. Add `Into<Expr>` for each Expr sub-type to make it easier to turn a proper struct into its `Expr` variant
3. Added `ExprVisitor` pattern
4. Implemented `ExprVisitor` to perform policy expr execution, replaced `pub(crate) eval()` func
Currently `ExprVisitor` is implemented on `Env<'_>`, but as is mentioned in the RFD, we might want other "visitors" on an Expr tree. In a subsequent PR as it becomes relevant, I recommend changing it so `Executor` implments `ExprVisitor` and the `env.rs` functions like `binary_primitive_op` are changed to take a `&Executor`. This way, additional structs that take an `Env` …

refactor PolicyExpr to use Visitor Pattern

---

hipcheck/src/policy/config_to_policy.rs
hipcheck/src/policy/test_example.kdl
hipcheck/src/policy_exprs/env.rs
site/content/docs/guide/plugin/policy-expr.md

fix: update language on handling of lambdas

---

Cargo.lock
Cargo.toml
plugins/fuzz/Cargo.toml
plugins/fuzz/src/main.rs
plugins/github_api/src/data.rs
sdk/rust/src/mock.rs

Resolves #482 .
This "analysis" is pretty simple, just forwards the "fuzz" query response from the `github_api` plugin.
I updated the SDK `mock.rs` to expect a response type of `Result<impl Serialize>` instead of `Result<Into<Value>>` in order to operate with the same expectations as the "query value" field.

feat: add fuzz plugin

---

hipcheck-sdk-macros/src/lib.rs
plugins/activity/Cargo.toml
plugins/activity/src/main.rs
plugins/dummy_rand_data_sdk/src/main.rs
plugins/dummy_sha256_sdk/src/main.rs
sdk/rust/src/plugin_engine.rs

Resolves #501 .
Adds the `fn record_concern` to `PluginEngine`, so that query endpoints can add concerns to be passed along with the return value of the query.
Fixes a few bugs, such as "default" queries not getting an empty-string name in the SDK macros crate.

feat: enable SDK plugins to report concerns

---

Cargo.lock
Cargo.toml
plugins/entropy/Cargo.toml
plugins/entropy/src/error/context.rs
plugins/entropy/src/error/mod.rs
plugins/entropy/src/linguist/db.rs
plugins/entropy/src/linguist/fs.rs
plugins/entropy/src/linguist/mod.rs
plugins/entropy/src/main.rs
plugins/entropy/src/metric.rs
plugins/entropy/src/types.rs
plugins/linguist/Cargo.toml
plugins/linguist/src/fs.rs
plugins/linguist/src/linguist.rs
plugins/linguist/src/main.rs

Resolves #489 .
`entropy::error` module is directly copied from Hipcheck core `error` module, can be ignored. Similarly, `entropy::linguist::{mod.rs, file.rs}` are copied from Hipcheck core with minimal alteration.
This PR adds the entropy plugin, which relies on a "lingust" analysis to determine whether or not a file is likely a source code file. This PR checks in a linguist plugin, but due to performance concerns, the entropy plugin currently does not use that analysis. Instead, it runs its own internal `salsa` database similar to how linguist results have been memo-ized in Hipcheck core. In the future, when #502 is implemented, we can modify entropy and churn plugins to do things "properly" by having the linguist plugin as a dependency and requesting the source code determination from …

feat: add Entropy plugin and Linguist plugin

---

Cargo.lock
Cargo.toml
plugins/github_api/plugin.kdl
plugins/review/Cargo.toml
plugins/review/plugin.kdl
plugins/review/src/main.rs

Resolves #518 
Adds a review plugin. This is mainly a refactor of the code found in `hipcheck/src/analysis.mod.rs` and `hipcheck/src/metrics/review.rs`.
Adds `plugin.kdl` manifest files for the github_api and review plugins.

feat: Adds review plugin

---

Cargo.lock
Cargo.toml
config/Hipcheck.kdl
plugins/binary/Cargo.toml
plugins/binary/plugin.kdl
plugins/binary/src/binary_detector.rs
plugins/binary/src/error/context.rs
plugins/binary/src/error/mod.rs
plugins/binary/src/fs.rs
plugins/binary/src/main.rs

Resolves #526 .
`binary_detector.rs`, the `error` crate and `fs.rs` are all direct copies of code from the Hipcheck core codebase.

feat: added binary analysis plugin

---

plugins/git/src/parse.rs

Resolves #538 
The `commits()` query for the `git` plugin now correctly returns all commits to a repo, not just the first commit.
The error originated when we removed commit signer information during the refactor of code from `hipcheck/src/data/git/parse.rs` to `plugins/git/src/parse.rs`. The lines that parse the singer name and key were removed from the git log commit parser function `commit()`, which caused the parser to look for the incorrect number of lines to the next commit. The `commits()` function that was supposed to repeat the `commit()` function for each commit in the git log consequently exited early after only adding the first commit to the returned `Vec` of commits.
These lines have been restored, which fixed the bug.

fix: Git log commit parser now returns more than one commit.

---

hipcheck/src/policy_exprs/json_pointer.rs

Resolves #524
This PR adds initial support for reading type-annotated data from JSON objects returned by a Plugin.
Two new data types are supported: `jiff::Zoned` and `jiff::Span`.
This implementation expects the JSON to follow a particular format: the data will consist of a JSON object with two required fields, `format` and `data`. `format` must contain a string that references a known format; this PR adds support for `"date-time"` and `"duration"`. These names are adopted to match JSON Schema's naming. `data` must contain the data; for both of these added data types, they are represented as JSON strings.
References
- https://json-schema.org/understanding-json-schema/reference/string#dates-and-times

feat: Support Spans and DateTimes in JSON Pointer injection

---

plugins/affiliation/src/org_spec.rs
plugins/affiliation/test/example_orgs.kdl
plugins/affiliation/test/test_orgs.kdl

Resolves #522 
The `example_orgs.kdl` file in the `affiliation` plugin now contains the full list of orgs found in the `config/Orgs.toml` file used by the older affiliation metric. The previous `example_orgs.kdl`, with a shorter list of orgs, has been renamed to `test_orgs.kdl` for use in testing.

chore: Adds full org list to example_orgs.kdl in affiliation plugin

---

Cargo.lock
hipcheck/src/plugin/retrieval.rs
plugins/review/plugin.kdl
plugins/review/src/main.rs
sdk/rust/Cargo.toml
sdk/rust/src/plugin_engine.rs

Resolves #547 . Resolves #503 . 
Separated into two commits - one fixes the rust SDK's handling of errors, the other updates the review plugin to run properly.

fix review plugin and SDK error handling

---

Cargo.lock
Cargo.toml
hipcheck/src/engine.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/retrieval.rs
plugins/churn/Cargo.toml
plugins/churn/plugin.kdl
plugins/churn/src/error/context.rs
plugins/churn/src/error/mod.rs
plugins/churn/src/linguist/db.rs
plugins/churn/src/linguist/fs.rs
plugins/churn/src/linguist/mod.rs
plugins/churn/src/main.rs
plugins/churn/src/metric.rs
plugins/churn/src/types.rs

Resolves #520 .
As with the entropy plugin, this lifts its `error::*`, `types.rs` and `linguist::{fs.rs, mod.rs}` almost directly from Hipcheck core. 
The `metric.rs` file is lifted almost directly from `plugins/entropy/src/metric.rs`.
The configuration requires `langs-file` to be present, but also optionally allows two additional args for a custom default query. if either of the args are present, the other is expected and the parsing code reflects that.

feat: add churn plugin

---

config/Hipcheck.kdl
hipcheck/src/plugin/plugin_manifest.rs
hipcheck/src/plugin/retrieval.rs
hipcheck/src/policy/policy_file.rs
hipcheck/src/session/mod.rs
hipcheck/src/util/kdl.rs

This change set improves the ergonomics of run 'local' plugins. Rather than running them at the path reachable in a provided Policy file, hipcheck now copies the entrypoints and plugin manifest files to the same cache locations that downloaded plugins would use.
Here is what `tree ~/Library/Caches/hipcheck/plugins` looks like on macOS after running hipcheck:
I deleted everything in `~/Library/Caches/hipcheck/plugins` before this run
I used the config on this branch in `config/Hipcheck.kdl` for testing this branch
This branch also added manifest paths to `binary` and `churn` to `config/Hipcheck.kdl` and updated the policy expression for `review`, in order to allow `hipcheck` to successfully complete its analysis with the config in the repo

feat: improve experience when using local plugins

---

config/Hipcheck.kdl
hipcheck/src/plugin/retrieval.rs
plugins/affiliation/plugin.kdl
plugins/affiliation/src/main.rs
plugins/git/src/data.rs
plugins/git/src/local.rs
plugins/git/src/main.rs

Resolves #549 
Updates affiliation plugin to run properly.
Because we have not yet implemented batching for queries, this PR adds temporary "local" functions to the git plugin, which do the same thing as existing async query functions but are not queries. It also adds new "batch" queries that call these local functions instead of relying on nested queries and can process more than one commit or contributor at once.
The code in the affiliation plugin has been updated to use these temporary queries instead of making looped calls to the regular queries. Once batching has been implemented, we can remove the temporary functions and change the execution code for affiliation back.

chore: Makes changes needed for affiliation plugin to run

---

Cargo.lock
config/Hipcheck.kdl
hipcheck/src/plugin/retrieval.rs
plugins/activity/src/main.rs
plugins/binary/src/main.rs
sdk/rust/Cargo.toml
sdk/rust/src/lib.rs
sdk/rust/src/types.rs

This pull requrest adds support for running `mitre/activity` via the new plugin infrastructure and tweaks the default config `config/Hipcheck.kdl` to enable running this plugin via the default config
During the development of this feature, I hit a couple of `unreachable!()` blocks in the code that evaluates policy expressions, so I added a new error type `MismatchedTypes(Box<Primitive>, Box<Primitive>, String)` to `hipcheck/src/policy_exprs/errors.rs` to make it clearer when mismatched types are compared
To make it easier for users to work with timestamp data, specifically when working with `jiff::Span` and `jiff::Zoned` and will allow us to more easily enable custom JSON objects that are opaque to the user in the future

feat: added support for running "mitre/activity" as a plugin

---

plugins/git/src/main.rs
plugins/git/src/parse.rs

fix: Make Git parser handle meta lines in chunk

---

plugins/git/src/main.rs
plugins/git/src/parse.rs

Diff parser bugfixes

---

Cargo.lock
hipcheck/src/plugin/plugin_manifest.rs
plugins/activity/Cargo.toml
plugins/activity/plugin.kdl
plugins/affiliation/Cargo.toml
plugins/affiliation/plugin.kdl
plugins/git/Cargo.toml
plugins/git/plugin.kdl
plugins/review/Cargo.toml
plugins/review/plugin.kdl
plugins/typo/Cargo.toml
plugins/typo/plugin.kdl

With migration away from legacy analyses largely complete, plugin binaries no longer need _sdk in their name. All plugins at this point rely on the sdk!

chore: removed *_sdk from plugin binary names

---

Cargo.lock
config/Hipcheck.kdl
config/Hipcheck.toml
hipcheck-sdk-macros/Cargo.toml
hipcheck-sdk-macros/src/lib.rs
hipcheck/src/analysis/score.rs
hipcheck/src/config.rs
hipcheck/src/engine.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/retrieval.rs
hipcheck/src/plugin/types.rs
plugins/entropy/src/main.rs
plugins/review/src/main.rs
sdk/rust/src/plugin_engine.rs

Resolves #559 . Resolves #579 .
Updates `entropy` plugin to run smoothly, and also rips out the `MITRE_LEGACY_PLUGINS` infrastructure from Hipcheck core, as after this there are no more legacy plugin implementations.
Separate commit adds outbound chunking to hipcheck core and SDK, which was not previously implemented causing too-large gRPC messages to crash the analysis.
Also replaces a lot of `println/eprintln` calls with `log::{warn, error, trace, debug}`

fix: entropy plugin exec and remove legacy plugin handling

---

hipcheck/src/policy/config_to_policy.rs
hipcheck/src/policy/test_example.kdl
plugins/binary/src/main.rs

fix: change binary plugin to return val policy expr can understand

---

hipcheck/src/policy_exprs/json_pointer.rs

The previous implementation of JSON pointer injection for datetime and span data was incorrect. In the prior implementation, the datetime or span data needed to be provided as an object with two fields: `field` and `data`, where `field` specifies the type to convert the `data` field into. The correct implementation is to simply try converting into one, then the other, and to then fail if neither succeeds. They have completely distinct string representations, so there is not a possibility of confusable conversion into the *wrong* type with this approach.
In the future we can and should update this implementation to incorporate the JSON schema data on what type is intended. I believe confusion on the use of JSON schema here (which *does* use the `field`/`data` pattern described above, but …

fix: Fix injection logic for datetime and span

---

hipcheck/src/engine.rs
hipcheck/src/main.rs

The `backoff_interval` was causing failures to run on MacOS with a `Reached max spawn attempts for plugin...` error. This fix increases the `backoff_interval_micros` value to allow enough time for a connection to made for the plugin.

fix: backoff_interval adjusted for MacOS

---

hipcheck/src/analysis/score.rs
hipcheck/src/report/mod.rs
hipcheck/src/report/report_builder.rs

This commit has two benefits, one is to eliminate a lot of the old reporting code which special-cased the legacy analyses, now that those have been entirely excised. The other is to improve the error reporting in both the success and failure cases.
There is still more that could be done to make these messages more explanatory, but this is a start.

feat: Improve reporting messages.

---

hipcheck/src/source/git.rs
plugins/affiliation/src/main.rs
plugins/affiliation/test/example_orgs.kdl

Changes the concern reporting for the affiliation plugin to include contributor name and e-mail. This allows for better understanding of why a contributor is concerning. Concerns go from
`Contributor John Smith has count 2`
to 
`Contributor John Smith (jsmith@mail.com) has count 2`
Also updates `/plugins/affiliation/test/example_orgs.kdl` to use a general "independent" strategy instead of a specific one we use for testing. The specific one is kept in `/plugins/affiliation/test/test_orgs.kdl`

chore: Adds e-mail to affiliated concern reporting

---

plugins/git/src/main.rs
plugins/git/src/parse.rs
plugins/git/src/util/git_command.rs

Resolves a few bugs in the `plugins/git` diff parser that I encountered while trying to run `plugins/entropy` on `numpy@no version`.
1. Our format specifier for `get_commits()` caused GPG key info to be printed and parsed, but locally I was getting an error in the GPG processing C code in `git`. Other team member got a different error, with git seemingly trying to do validation against GPG signatures in the git history when GPG was not set up on his machine.
2. Some diffs that just delete a file do not have the 1-2 lines prefixed with `+++` or `---` between the patch metadata and patch chunks. We were naively using `opt(line)` to capture these, which would eat up the start of another `diff` in some cases. Now we check for those lines explicitly. 
3. Some other commits (such as those just …

fix: bugs in detecting empty git diffs and end of patch meta block

---

hipcheck/src/report/mod.rs
hipcheck/src/report/report_builder.rs
hipcheck/src/shell/mod.rs

Resolves #598 .
Removed unused `message` field from Analysis struct for reports, it was just printing the default policy expr, which may not even be the policy used in the analysis. For now removed the explanation print from the report emitting code, we will re-add an explanation once we have a system for auto-generating policy expr explanations.

fix: remove double-printing of policy exprs

---

hipcheck/src/report/mod.rs
hipcheck/src/report/report_builder.rs
hipcheck/src/shell/mod.rs

This reverts commit c82797e4e6be9b9a9b4ecbc78f63818040fcc162.

chore: revert "fix: remove double-printing of policy exprs"

---

hipcheck/src/plugin/manager.rs

Closes #583 
With the current codebase and plugins that we have, this check works, but if an entrypoint is not kicking off a binary and runs a docker image or runs `python3 -m ...` or does anything outside of how our plugins work today, this will likely fail. Maybe this should just log a warning that it could not find the provided file and still try to spawn the plugin?

feat: improve error handling if plugin entrypoint does not exist

---

dist/Containerfile

The `Containerfile` had quietly been broken. It was missing the `ca-certificates` package, which `curl` needed to run later steps. This commit adds the missing package.
It also bumps the `Containerfile` to version `3.7.0`, the current version.

fix: Fix broken Containerfile

---

hipcheck/src/plugin/manager.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/plugin_manifest.rs
hipcheck/src/plugin/retrieval.rs

The existing code treated the `entrypoint` string as a `PathBuf`, when in reality it could be a cmdline string with spaces and arguments. 
This PR updates the handling to reflect this, and also modifies the `retrieve_local_plugin()` behavior to only copy the plugin entrypoint binary if it is a path. For instance, if the entrypoint started as `docker ...`, we wouldn't copy the `docker` binary because does not exist as a path. 
Also updated the warning in `start_plugin()` to warn if the binary component of `entrypoint` cannot be found with `which`.

fix: handling of plugin entrypoint string

---

config/Hipcheck.kdl
plugins/affiliation/src/main.rs
plugins/typo/src/main.rs

chore: rename typo-file-path and orgs-file-path

---

hipcheck/Cargo.toml
hipcheck/src/plugin/retrieval.rs

Here is a video of this branch having two macOS `hc check` commands work at the same time!
https://github.com/user-attachments/assets/9c4a6355-8817-421e-85e4-00f903140946
To trigger this bug on macOS, the following steps were the easiest way I could find to reliably trigger this
1. Have a plugin running
2. While it is still running, copy over the running binary location on disk
3. Attempt to run this new binary (it will fail)
To avoid this issue, `hc` now checks the `sha256` of the source and destination before copying the files and skips the copy if the hashes are identical

fix: reduce unnecessary filesytem copies when spawning plugins

---

hipcheck/src/plugin/types.rs
sdk/rust/src/plugin_engine.rs

Replace use of `drain()` with custom `drain_at_most_n_bytes()` to ensure we don't try to drain from the middle of a multi-char character and cause a panic. Added some test cases.

feat: improve chunking method in sdk

---

hipcheck/src/plugin/retrieval.rs
hipcheck/src/util/fs.rs

I tested simultaneous execution of Hipcheck on Windows, and found that Windows won't let us overwrite plugins in the cache as we have been if another HC instance is using that plugin. 
I pulled in some changes @patrickjcasey wrote to do sha256-hash checking, and set the logic so that it would only do this on Windows so other OSes don't take the performance hit.

fix: add hash check when copying local plugins on windows

---

site/content/docs/rfds/0009-batch-queries.md
site/content/docs/rfds/0010-submit-chunking.md

feat: add RFD describing proposed batched query feature

---

hipcheck/src/analysis/score.rs
hipcheck/src/benchmarking.rs
hipcheck/src/cli.rs
hipcheck/src/config.rs
hipcheck/src/engine.rs
hipcheck/src/main.rs
hipcheck/src/plugin/retrieval.rs
hipcheck/src/policy/mod.rs
hipcheck/src/report/report_builder.rs
hipcheck/src/session/mod.rs
hipcheck/src/shell/mod.rs

Resolves #647 .
First commit: 
- Reviewed use of `print-timings` crate, fixed one compilation error, included timing prints in plugin infrastructure for future optimization efforts.
Second commit:
- Noticed that `hc scoring` which simply prints the normalized weight tree for a policy file required using fake data to spin up a sham `Session` object. Added a few functions to `config.rs` to be able to get a weight tree without a `Session` object. Now, we can get an "unresolved" but normalized weight tree, and then the existing `analysis_tree()` salsa function just applies the plugin's default policy expr to each analysis node without a policy.

Improve `hc scoring` and update use of `print-timings` feature

---

config/Hipcheck.kdl

The example policy file `config/Hipheck.kdl` was still using the older `foo-file-path` label for some of the additional file locations, instead of `foo-file`. This fixes that so the example policy file works correctly.

chore: Updates file path tags in example policy file

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/config.rs
hipcheck/src/engine.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/types.rs
hipcheck/src/policy_exprs/expr.rs
hipcheck/src/policy_exprs/mod.rs
hipcheck/src/report/mod.rs
hipcheck/src/report/report_builder.rs
hipcheck/src/score.rs
hipcheck/src/session/mod.rs
plugins/activity/src/main.rs

Resolves #677 .
This PR submits 2 commits, the long form of each commit message explains their purpose.
Broadly, this swaps `String` with `Expr` where applicable in the codebase. 
One major design decision was to not have `PolicyFile` itself try to parse the policy expressions and do the parsing when we transfer "policy expression" Strings from that file into the broader Hipcheck environment.

integrate type checking, and add graceful handling of plugin startup errors

---

plugins/activity/dist.toml
plugins/affiliation/dist.toml
plugins/binary/dist.toml
plugins/churn/dist.toml
plugins/entropy/dist.toml
plugins/fuzz/dist.toml
plugins/git/dist.toml
plugins/github/dist.toml
plugins/identity/dist.toml
plugins/linguist/dist.toml
plugins/npm/dist.toml
plugins/review/dist.toml
plugins/typo/dist.toml

This fixes a build failure during plugin release caused by a missing protobuf compiler.

fix: Ensure plugins have protoc installed for dist.

---

site/static/dl/plugin/mitre/activity.kdl
site/static/dl/plugin/mitre/affiliation.kdl
site/static/dl/plugin/mitre/binary.kdl
site/static/dl/plugin/mitre/churn.kdl
site/static/dl/plugin/mitre/entropy.kdl
site/static/dl/plugin/mitre/fuzz.kdl
site/static/dl/plugin/mitre/git.kdl
site/static/dl/plugin/mitre/github.kdl
site/static/dl/plugin/mitre/identity.kdl
site/static/dl/plugin/mitre/linguist.kdl
site/static/dl/plugin/mitre/npm.kdl
site/static/dl/plugin/mitre/review.kdl
site/static/dl/plugin/mitre/typo.kdl

In the future we'll automate this. These are the download manifests for the new plugins, which are the mechanism that users of Hipcheck will use to incorporate these plugins themselves. It tells Hipcheck where to find the proper bundle for a specific plugin architecture + version combo.

feat: Add download manifests for all new plugins.

---

config/Hipcheck.kdl
hipcheck/src/plugin/download_manifest.rs
hipcheck/src/plugin/plugin_manifest.rs
hipcheck/src/plugin/retrieval.rs
plugins/fuzz/plugin.kdl

This fixes plugin downloading by ensuring plugins are downloaded and unarchived to the correct directory, and also fixes an error in the plugin manifests for `fuzz@0.1.0`, bumping to `0.1.1`.

fix: Fix plugin downloading and prep bump for fuzz

---

config/local.Hipcheck.kdl
hipcheck/src/engine.rs
hipcheck/src/main.rs
hipcheck/src/plugin/manager.rs
hipcheck/src/plugin/plugin_manifest.rs
hipcheck/src/plugin/retrieval.rs
hipcheck/src/plugin/types.rs

Discovered a bug in the entry selection process from the plugin's download manifest, such that the desired version was not checked and the first entry with a matching arch was returned. Additionally, downloaded plugin.kdl files have entrypoints that are relative to the parent dir, but Hipcheck core does not change working directory for the process so we don't find the right plugin binary. This commit appends the working dir to the entrypoint binary and canonicalizes it so it can be resolved. The new implementation works but disallows the use of arguments in the entrypoint or use of docker containers. The spawning code will need to be addressed at greater length in a subsequent commit.

fix: get proper version from download manifest and spawn with canonical path

---

site/content/blog/2024-11-04-hipcheck-3.8.0-release.md
site/templates/partials/prose-config.tera.html

Don't publish until `hc` 3.8.0 and `hipcheck-sdk` 0.2.0 are released.

chore: 3.8.0 announcement post

---

Cargo.lock
hipcheck/src/plugin/manager.rs
hipcheck/src/plugin/retrieval.rs

Resolves #706 . Resolves #707 .
Some quality of life changes for plugins.
- Add the plugin's cache path to the plugin's process PATH to help plugin process find artifacts when running
- Add `force: bool` to plugin downloading function, and use existing plugin with right version in cache if exists and `force=false` instead of pulling and decompressing every time
- Change plugin bundle extraction to only copy up artifacts from a subdir if it matches name of the bundle minus the compression extension. Previous impl could accidently copy unrelated files if passed `extract_dir` contained other subdirs already.

plugin download/execution improvements

---

site/content/docs/guide/config/policy-file.md
site/content/docs/guide/plugins/mitre-entropy.md

Resolves #711 . Resolves #712.
Fixed spelling errors in `mitre-entropy.md` file and updated the policy-expressions link in `policy-file.md` file in the Complete Guide.

docs: Fixed spelling and updated link in docs

---

Cargo.lock
plugins/git/Cargo.toml

Resolves #733 .
Replacing our custom nom parser for git data with `gix` implicitly introduced a dependency on `cmake` to build `zlib-ng`. This commit changes the features of `gix` to use the system zlib instead if present.

fix: remove cmake build dep from git plugin

---

hipcheck/src/cli.rs
hipcheck/src/session/mod.rs
hipcheck/src/source/mod.rs
hipcheck/src/target/mod.rs
hipcheck/src/target/resolve.rs
hipcheck/src/target/types.rs

Resolves #743 .
This PR simply refactors the existing logic for target resolution into the form proposed by RFD5. In a subsequent PR I will add fuzzy version checking for packages and code for getting the newest version of an npm package by parsing the JSON object.
There are slight improvements to the selection of what git ref to target based on what seed we resolved from in `get_checkout_target()`.

feat(refactor): initial RFD5 impl, slight refspec handling improvement

---

hipcheck/src/source/git.rs
hipcheck/src/target/resolve.rs
hipcheck/src/target/types.rs

Resolves #753, #755, and #256 .
If during resolution we have a `Package` with a non-null version, we try to resolve to a tag in the repo with a variety of combinations of version specifier and package name. Verified that this works against `-t nmp duplexer2@0.1.4`, which previously gave us problems. Our previous dirty fix of checking `v<VERSION>` inside of `git::checkout()` has been removed.
Edit: Based on discussion in the Slack channel, I've augmented the logic. If a package is specified with no version and no ref, we will use a forgiving semver regex to try and find the "latest" version tag in the repo.

feat: improved version-to-git-tag matching scheme

---

Cargo.lock
hipcheck-common/Cargo.toml
hipcheck-common/proto/hipcheck/v1/hipcheck.proto
hipcheck-common/src/chunk.rs
hipcheck-common/src/error.rs
hipcheck-common/src/types.rs
hipcheck/Cargo.toml
hipcheck/src/main.rs
hipcheck/src/session/mod.rs
plugins/activity/Cargo.toml
plugins/affiliation/Cargo.toml
plugins/binary/Cargo.toml
plugins/churn/Cargo.toml
plugins/entropy/Cargo.toml
plugins/fuzz/Cargo.toml
plugins/git/Cargo.toml
plugins/github/Cargo.toml
plugins/identity/Cargo.toml
plugins/linguist/Cargo.toml
plugins/npm/Cargo.toml
plugins/review/Cargo.toml
plugins/typo/Cargo.toml
sdk/rust/Cargo.toml
sdk/rust/src/error.rs
sdk/rust/src/plugin_engine.rs
xtask/src/task/mod.rs

- Added support for chunking Query submissions
- Added test for submission chunking
I just want to ensure that adding an enum variant to `QueryState` is not considered a breaking change. Also since this changes `hipcheck-common`, does its version need be incremented or do we just handle that when it comes time to cut a release

feat: implemented submit chunking for RFD #0010

---

Cargo.lock
plugins/activity/local-plugin.kdl
plugins/activity/plugin.kdl
plugins/affiliation/local-plugin.kdl
plugins/affiliation/plugin.kdl
plugins/churn/local-plugin.kdl
plugins/churn/plugin.kdl
plugins/entropy/local-plugin.kdl
plugins/entropy/plugin.kdl
plugins/git/Cargo.toml
plugins/git/src/git.rs
plugins/git/src/main.rs
plugins/identity/local-plugin.kdl
plugins/identity/plugin.kdl
site/content/docs/guide/plugins/mitre-git.md

12/30 - The PR has changes to the `git` plugin that uses an LRU cache functionality. The configurability of the size of the cache would come after the #662 changes are pulled.

CLRU added for git plugin

---

Cargo.lock
hipcheck/src/cache/plugin.rs
hipcheck/src/cache/repo.rs

first implementation of the list function for plugins

feat: implemented list function for plugins

---

hipcheck-common/proto/hipcheck/v1/hipcheck.proto
hipcheck-common/src/chunk.rs
hipcheck-common/src/types.rs
hipcheck/src/cache/plugin.rs
hipcheck/src/engine.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/types.rs
hipcheck/src/score.rs
plugins/affiliation/src/main.rs
plugins/typo/src/main.rs
sdk/rust/src/engine.rs

This pull request implements the majority of the guts of RFD #0009
- `hipcheck.proto` has been updated to make Query.key and Query.output
"repeated string fields"
- `hipcheck.proto` has been updated to add a new field, split, to Query
- chunking of GRPC messages now maintains initial ordering of fields
when chunking is required
- additional unit tests added for chunking algorithm
- added `batch_query` function to rust SDK

rfd9 implementation

---

hipcheck/src/policy_exprs/env.rs
hipcheck/src/policy_exprs/error.rs
hipcheck/src/policy_exprs/expr.rs
hipcheck/src/policy_exprs/mod.rs
hipcheck/src/report/mod.rs
hipcheck/src/report/report_builder.rs
hipcheck/src/score.rs
hipcheck/src/shell/mod.rs
plugins/activity/src/main.rs
plugins/affiliation/src/main.rs
plugins/binary/src/main.rs
plugins/churn/src/main.rs
plugins/entropy/src/main.rs
plugins/fuzz/src/main.rs
plugins/review/src/main.rs
plugins/typo/src/main.rs

Part of Issue #383 . Adds primitive English-language summaries of policy expressions for failed plugins.
The policy expression level English parser requires that the "top level" of a policy expression be a function that takes two arguments (as the comparison operator functions that return a Boolean all do) where at least one argument is a Primitive type. It then applies a recursive English parser to each component of the policy expression, drilling into nested functions and lambdas as needed. After that, it evaluates whichever of the top level function's arguments is not a Primitive as a policy expression using the value returned by the plugin, to get the Primitive that the top level function is comparing the other Primitive to. The English language description of the function and the …

feat: Add English language parsing of failure messages

---

hipcheck/dist.toml
hipcheck/src/cli.rs
hipcheck/src/main.rs
hipcheck/src/setup.rs
site/content/docs/contributing/developer-docs/repo-structure.md
site/content/docs/guide/cli/hc-setup.md
site/content/docs/guide/cli/hc-update.md

During hc setup write config files from memory, without local dirs or remote source.
Resolves #782

fix(setup): write configuration files directly from memory

---

site/content/docs/guide/cli/general-flags.md
site/content/docs/guide/config/exec-file.md

chore: add exec.kdl docs

---

plugins/affiliation/src/main.rs
plugins/git/src/data.rs
plugins/git/src/main.rs
sdk/rust/src/engine.rs

This PR completes the implementation of RFD9 outside of #821.
I experimented with using `batch_query` in `mitre/affiliation`, but on real repos, I found it was typically about 10x slower than our current implementation, due the sheer number of GRPC calls that were needed.
Based on this, I updated `mitre/affiliation` and removed the `TODO` sections around batching and also removed code related to custom chunking, as `hipcheck-common` now fully handles that. I also added a query to `mitre/git` that enables querying for all commits, as well as the author and committer of each commit. I also improved the ergonomics of checking each contributor for affiliation and reduced the amount of comparisons that are needed. I spent a few minutes benchmarking this branch with `hyperfine` and found this …

update mitre/git and mitre/affiliation for RFD9

---

Cargo.lock
hipcheck/Cargo.toml

Resolves #840 by updating the version of the `indicatif` crate to 0.17.11.

fix: Updates indicatif to v. 0.17.11 to resolve thread safety error.

---

hipcheck-common/Cargo.toml
hipcheck-common/src/chunk.rs
hipcheck-common/src/types.rs
hipcheck/Cargo.toml

Resolves #821 .
Fixes some logic in hipcheck-common to support backwards compatibility in the form of communication with plugins using the pre-RF9 hipcheck-common. I have wrapped the behavior in a `rfd9-compat` feature so that it can be turned off / removed in the future if we decide backwards compatibility is no longer important.
I will spend time this week fleshing out ways to test that this is correct more concretely, but this does pass the following:
- all pre-RFD9 plugins
- all post-RFD9 plugins
- pre-RFD9 `git`, post-RFD9 `churn`
- post-RFD9 `git`, pre-RFD9 `churn`

fix: backwards compatibility between RFD9 and prior plugins

---

hipcheck/src/target/purl.rs
xtask/src/task/buf.rs
xtask/src/task/ci.rs

I noticed `cargo xtask buf` was not working on `main`, so I resolved the issues. While I was resolving the issue, I also added support to `cargo xtask ci` to run the `buf lint` command and print out `buf --version`. I also noticed a missing SPDX License Identifier and added that, while I was here

cargo xtask buf fixes

---

config/local.release.Hipcheck.kdl
plugins/activity/local-release-plugin.kdl
plugins/affiliation/local-release-plugin.kdl
plugins/binary/local-release-plugin.kdl
plugins/churn/local-release-plugin.kdl
plugins/entropy/local-release-plugin.kdl
plugins/fuzz/local-release-plugin.kdl
plugins/git/local-release-plugin.kdl
plugins/github/local-release-plugin.kdl
plugins/identity/local-release-plugin.kdl
plugins/linguist/local-release-plugin.kdl
plugins/npm/local-release-plugin.kdl
plugins/review/local-release-plugin.kdl
plugins/typo/local-release-plugin.kdl

- adds `local.release.Hipcheck.kdl` , which is a copy of `local.Hipcheck.kdl` with paths to `local-release-plugin.kdl` instead of `local-plugin.kdl`
- adds `local-release-plugin.kdl` file to each plugin, which specifies release binary paths
The above changes make it more convenient to test the release versions of binaries
I tested these files by doing the following:
```bash
rm -rf ~/.cache/hipcheck/plugins && cargo clean # to ensure there are no cached plugins or build artifacts
cargo build --release --workspace
./target/release/hc check --policy ./config/local.release.Hipcheck.kdl https://github.com/mitre/hipcheck
```

feat: adds config files for testing release binaries

---

hipcheck/src/plugin/mod.rs

Resolves #846 by changing a `remove()` to a `get().cloned()`. This is a short term fix until we can fully implement tracking of plugins by version.

fix: Removes panic when looking for multiple versions of the same plugin

---

site/content/docs/guide/making-plugins/_index.md
site/content/docs/guide/making-plugins/release.md

chore(docs): document how to package and publicly release plugins

---

config/local.Hipcheck.kdl
config/local.release.Hipcheck.kdl
plugins/activity/local-plugin.kdl
plugins/activity/local-release-plugin.kdl
plugins/affiliation/local-plugin.kdl
plugins/affiliation/local-release-plugin.kdl
plugins/binary/local-plugin.kdl
plugins/binary/local-release-plugin.kdl
plugins/churn/local-plugin.kdl
plugins/churn/local-release-plugin.kdl
plugins/entropy/local-plugin.kdl
plugins/entropy/local-release-plugin.kdl
plugins/fuzz/local-plugin.kdl
plugins/fuzz/local-release-plugin.kdl
plugins/git/local-plugin.kdl
plugins/git/local-release-plugin.kdl
plugins/github/local-plugin.kdl
plugins/github/local-release-plugin.kdl
plugins/identity/local-plugin.kdl
plugins/identity/local-release-plugin.kdl
plugins/linguist/local-plugin.kdl
plugins/linguist/local-release-plugin.kdl
plugins/npm/local-plugin.kdl
plugins/npm/local-release-plugin.kdl
plugins/review/local-plugin.kdl
plugins/review/local-release-plugin.kdl
plugins/typo/local-plugin.kdl
plugins/typo/local-release-plugin.kdl

- updated all local.*.kdl files to use version `0.0.0` to prevent overwriting released plugins
By doing this, I see two main benefits:
- all of the `local.*.kdl` files no longer need to be updated each time a plugin version is bumped
- cached released plugins are not overwritten with development plugins
closes #844

fix: local plugins no longer overwrite released plugins

---

config/Hipcheck.kdl

Additional change to make `Hipcheck.kdl` work until 3.10

chore: revert this prior to 3.10 release

---

plugins/activity/plugin.kdl
plugins/affiliation/plugin.kdl
plugins/binary/plugin.kdl
plugins/churn/plugin.kdl
plugins/entropy/plugin.kdl
plugins/fuzz/plugin.kdl
plugins/git/plugin.kdl
plugins/github/plugin.kdl
plugins/identity/plugin.kdl
plugins/linguist/plugin.kdl
plugins/npm/plugin.kdl
plugins/review/plugin.kdl
plugins/typo/plugin.kdl

Updating plugins' plugin.kdl versions and dependencies ahead of release.
All plugins had already had their `Cargo.toml` versions bumped earlier in the dev cycle, so this was just a process of updating the plugin.kdl files to match.

chore: bump plugin versions for release

---

hipcheck/src/plugin/retrieval.rs

I improved the error message that is printed when a `hc` is unable to find a plugin manifest for a particular plugin.
Original output:
Updated output:

fix: improve user experience when unable to find plugin download manifest

---

Cargo.lock
config/Hipcheck.kdl
dist/Containerfile
hipcheck/Cargo.toml
hipcheck/src/config.rs
hipcheck/src/policy/config_to_policy.rs
hipcheck/src/policy/test_example.kdl
site/config.toml
site/static/dl/install.ps1
site/static/dl/install.sh
site/static/dl/plugin/mitre/activity.kdl
site/static/dl/plugin/mitre/affiliation.kdl
site/static/dl/plugin/mitre/binary.kdl
site/static/dl/plugin/mitre/churn.kdl
site/static/dl/plugin/mitre/entropy.kdl
site/static/dl/plugin/mitre/fuzz.kdl
site/static/dl/plugin/mitre/git.kdl
site/static/dl/plugin/mitre/github.kdl
site/static/dl/plugin/mitre/identity.kdl
site/static/dl/plugin/mitre/linguist.kdl
site/static/dl/plugin/mitre/npm.kdl
site/static/dl/plugin/mitre/review.kdl
site/static/dl/plugin/mitre/typo.kdl

Resolves #798 .
Still todo: run `cargo xtask manifest` once plugins finish releasing.
We should make sure that running `hc --config ./config ...` works with this branch before committing.

chore: bump plugin versions in Hipcheck confs and Hipcheck version

---

hipcheck/src/policy_exprs/env.rs
hipcheck/src/policy_exprs/mod.rs
hipcheck/src/report/mod.rs
hipcheck/src/shell/mod.rs

Resolves #837 We now attempt to parse policy expressions into English-language explanations whether the plugin's analysis succeeded or failed (but not if it errored). If a policy expression cannot be parsed, an error message is logged and the default plugin explanation text is displayed instead.

feat: Adds English language parsing for successful analyses

---

hipcheck/src/init/mod.rs
hipcheck/src/main.rs
hipcheck/src/report/mod.rs
hipcheck/src/report/report_builder.rs
hipcheck/src/session/mod.rs
hipcheck/src/version.rs

This is the first step in removing unnecessary uses of `salsa` in hipcheck core.
closes #881

chore: replace VersionQuery with OnceLock and functions

---

hipcheck/src/cli.rs
hipcheck/src/main.rs
hipcheck/src/session/mod.rs

- Add a `Display` impl for `ConfigMode`.
- Log the inferred `ConfigMode` at INFO level at startup of `check` command.
- Use logging instead of `Shell` methods when falling back to Config TOML.
- Include path to policy file in context when reporting errors.

feat: Improve logging of policy file error messages

---

hipcheck/src/policy_exprs/mod.rs
plugins/churn/src/main.rs
plugins/entropy/src/main.rs

Finishing resolving #838 Adds simpler English phrases for the commonly occurring "count" and "percent" patterns. Changes default explanations for `churn` and `entropy` to better fit the new phrasing.

feat: Improve English phrasing of count and percent policy expressions.

---

.github/workflows/hipcheck.yml
README.md
dist-workspace.toml

Resolves #823 , Resolves #812 , Resolves #789 , Resolves #688 .
While in draft, I added a dummy commit to trigger the HC builds and tests that would not be triggered if I just updated the hipcheck.yml, so I have verified that our code running these updated actions will pass.

chore: CI improvements

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/plugin/types.rs
hipcheck/src/policy/mod.rs
hipcheck/src/util/fs.rs
plugins/affiliation/Cargo.toml
plugins/affiliation/src/main.rs
plugins/affiliation/src/org_spec.rs
plugins/binary/Cargo.toml
plugins/binary/src/binary_detector.rs
plugins/binary/src/error/mod.rs
plugins/binary/src/main.rs
plugins/churn/src/error/mod.rs
plugins/entropy/src/error/mod.rs
plugins/github/src/main.rs
plugins/linguist/Cargo.toml
plugins/linguist/src/error/mod.rs
plugins/linguist/src/linguist.rs
plugins/linguist/src/main.rs
plugins/typo/Cargo.toml
plugins/typo/src/languages.rs
plugins/typo/src/main.rs
plugins/typo/src/util/fs.rs
sdk/rust/src/error.rs

Relates to #880, in that this improves the error message, but doesn't fix the problem that plugin errors aren't attributed to the failing plugin.
- Print plugin errors with full context, like which file could not be opened.
- Clarify wording of some error messages.
- Add `miette` dependency to print helpful KDL parsing errors.

feat: Improve error message context from plugins

---

hipcheck/src/engine.rs
hipcheck/src/main.rs
hipcheck/src/plugin/manager.rs
hipcheck/src/plugin/mod.rs
hipcheck/src/plugin/retrieval.rs
hipcheck/src/plugin/types.rs

Resolves #880
Add plugin version to the `Plugin` struct so that it's available when starting plugins.
Also add logging when Hipcheck retrieves and starts plugins.

feat: Track plugin name and version when reporting startup errors

---

hipcheck/src/session/mod.rs
hipcheck/src/shell/mod.rs

Added a `Config` title to the Hipcheck output that indicates in each `check` run where the policy/config comes from to further help users track where their policy comes from. `HC_CONFIG` may be set by a previous user or forgotten, but it still treated as `FromUser` in provenance determination, so this kind of a message will inform the user of where the config is being pulled from.
Also standardized use of lowercase strings to `SpinnerPhase::start()`

chore: add policy location info to standard check output

---

site/content/blog/2025-02-11-hipchecks-ramp-of-maximum-configurability.md

This adds a blog post on Hipcheck's approach to configurability and the options available for changing what analyses run and how they run.

chore: "Maximum Configurability" blog post

---

.github/workflows/dco_merge_group.yml
.github/workflows/website-deploy.yml

A prior fix mistakenly added site deploys to run on merge queues. This fixes that by removing the workflow config item for it.

fix: Stop site deploy on merge queue.

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/engine/mod.rs
hipcheck/src/engine/salsa_cache.rs
hipcheck/src/main.rs
hipcheck/src/session/mod.rs
hipcheck/src/shell/mod.rs

- migrated from last `salsa` code on crates.io (0.16.1) to latest `salsa v3` code in https://github.com/salsa-rs/salsa
- moved engine.rs code into new engine module
- split out salsa caching logic into new file in `engine` module (`salsa_cache.rs`)
- all `salsa` events are logged at the `debug` level
- using `hipcheck-v<CURRENT_VERSION>` convention for tagging `mitre/salsa` to keep track of what commit of `salsa` is being used by `hipcheck`
- `#[salsa::db]` on a struct requires the struct to also be `Clone`
- `salsa::ParallelDatabase` no longer exists in `salsa`, as it is no longer needed
- using `#[salsa::tracked]` to mark a function for tracking via `salsa` is the new way to track functions. 
- `#[salsa::input]` is used to track input to `#[salsa::tracked]` functions and requires types …

feat: migrated to latest salsa v3 code

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/report/mod.rs
hipcheck/src/shell/mod.rs

Resolves #909  
Replaces the old method of printing human readable output to the shell with a new one that parses the existing `Report` struct (which is what we serialize and print as the JSON output) using MiniJinja and prints a single report String.

feat: Prints human output directly from Report

---

hipcheck-common/proto/hipcheck/v1/hipcheck.proto
hipcheck/src/main.rs
hipcheck/src/plugin/types.rs
plugins/activity/src/main.rs
plugins/affiliation/src/main.rs
plugins/affiliation/src/org_spec.rs
plugins/binary/src/binary_detector.rs
plugins/binary/src/main.rs
plugins/churn/src/main.rs
plugins/entropy/src/main.rs
plugins/git/src/main.rs
plugins/github/src/main.rs
plugins/identity/src/main.rs
plugins/linguist/src/linguist.rs
plugins/linguist/src/main.rs
plugins/review/src/main.rs
plugins/typo/src/languages.rs
plugins/typo/src/main.rs
sdk/rust/src/error.rs

Resolves #931
Add new variants to replace all existing uses of `Unspecified`, other than `serde_json` parse errors:
- `InternalError`
- `FileNotFound`
- `ParseError`
- `EnvVarNotSet`
- `MissingProgram`

refactor: Improve clarity of ConfigError variants

---

Cargo.lock
config/Hipcheck.kdl
hipcheck/Cargo.toml
hipcheck/src/policy/config_to_policy.rs
hipcheck/src/policy/test_example.kdl

Updates Hipcheck to point to and use the new plugin versions. Linguist was introduced as a dependent plugin, and churn/entropy no longer need a `langs-file` config.

chore: update hipcheck default plugin versions

---

site/content/blog/2025-02-21-hipcheck-3.11.0-release.md

Missing `&` on Unicode non-breaking space literal.

fix: Minor site blog post typo.

---

site/content/docs/getting-started/first-run.md
site/content/docs/guide/cli/hc-ready.md
site/content/docs/guide/config/policy-file.md
site/content/docs/guide/debugging/starting.md

Relates to #674
- Add links to `hc ready` docs where users might find it useful.
- Fix a minor typo in docs. "tha" -> "the"

docs: Document that hc ready starts plugins (implemented in #908)

---

.github/workflows/hipcheck.yml
.github/workflows/website-test.yml

Resolves #957 .
Merge queues trigger jobs based on the "required jobs" section of a branch's merge protections. Unfortunately, merge queues cannot detect when a workflow is "skipped", and so expects all of the required jobs to return success. Our current workflows decide at the top-level whether to run based on the modified files in the PR, so sometimes these jobs considered "required" by the merge queue do not fire, causing a deadlock. This PR moves the filtering into a job of the workflow, so now the workflow always "runs", but the relevant job will not unless any files in the given paths are modified.

chore: CI workflows always run, jobs do filtering

---

site/content/blog/2025-02-21-hipcheck-3.11.0-release.md
site/content/docs/guide/plugins/mitre-churn.md
site/content/docs/guide/plugins/mitre-entropy.md

Not to be merged until just prior to 3.11 release, contains changes to docs that become live with the new batch of plugins and new Hipcheck crate / binary releases.

chore(docs): update docs to reflect 3.11 changes

---

.github/workflows/hipcheck.yml
dist-workspace.toml

This commit does two things:
- Updates our Ubuntu runner (used for x86 Linux builds) to `ubuntu-22.04` instead of `ubuntu-20.04`. GitHub is in the process of sunsetting their `ubuntu-20.04` image. For now, dist hasn't changed the default runner for `x86_64-unknown-linux-gnu`, so we're overriding it here.
- Syncs the runner used for Apple Silicon macOS builds across dist and regular CI testing to always use `macos-14`. Previously, dist would use `macos-13`, which is x86 macOS, and cross compile to ARM. This didn't match what we did in our own regular CI testing. Now they match, which should hopefully reduce the chance of surprise errors at release time in the future.
Closes #924

feat: update and sync runners (ubuntu-22.04, macos-14)

---

.cargo/config.toml
.devcontainer/devcontainer.json
.github/workflows/hipcheck.yml

Using mold as a linker on x86-linux lead to the following gains on my system:
- ~10% faster debug builds
- ~5% faster release builds
```bash
cd /tmp && hyperfine --runs 2 \
--prepare 'cd ~/workspace/hipcheck/main && cargo clean' \
'cd ~/workspace/hipcheck/main && RUSTC_WRAPPER="" cargo build --workspace' \
--prepare 'cd ~/workspace/hipcheck/patrickjcasey/use-mold-linux && cargo clean' \
'cd ~/workspace/hipcheck/patrickjcasey/use-mold-linux  &&  RUSTC_WRAPPER="" cargo build --workspace'
```
```bash
cd /tmp && hyperfine --runs 2 \
--prepare 'cd ~/workspace/hipcheck/main && cargo clean' \
'cd ~/workspace/hipcheck/main && RUSTC_WRAPPER="" cargo build --workspace --release' \
--prepare 'cd ~/workspace/hipcheck/patrickjcasey/use-mold-linux && cargo clean' \
'cd …
```

chore: use mold as linker for x86_64-unknown-linux-gnu

---

plugins/activity/src/main.rs
plugins/affiliation/src/main.rs
plugins/binary/src/main.rs
plugins/churn/src/main.rs
plugins/entropy/src/main.rs
plugins/fuzz/src/main.rs
plugins/git/src/main.rs
plugins/github/src/main.rs
plugins/identity/src/main.rs
plugins/linguist/src/main.rs
plugins/npm/src/main.rs
plugins/review/src/main.rs
plugins/typo/src/main.rs
test-plugins/dummy_rand_data/src/main.rs
test-plugins/dummy_sha256/src/main.rs

Plugins can now accept unknown trailing arguments without failure. 
Allows for greater robustness when arguments get added.

fix: plugins accept and parse unknown trailing args

---

dist/Containerfile

fix: add missing mold dependency to dist/Containerfile

---

Cargo.lock
hipcheck-common/Cargo.toml
hipcheck/Cargo.toml
plugins/activity/Cargo.toml
plugins/binary/Cargo.toml
plugins/entropy/Cargo.toml
plugins/fuzz/Cargo.toml
plugins/git/Cargo.toml
plugins/github/Cargo.toml
plugins/linguist/Cargo.toml
plugins/typo/Cargo.toml
sdk/rust/Cargo.toml
test-plugins/dummy_rand_data/Cargo.toml

Used 'cargo machete' to identify unused dependencies. There were a few false positives which were added to an ignore list in the appropriate 'Cargo.toml' files.

chore: Removed unused dependencies.

---

Cargo.lock
hipcheck/Cargo.toml

I bumped salsa to the latest commit, which was 91 commits ahead of the `hipcheck-v3.11.0` tag. The `mitre/salsa` repo has been synced and the latest commit was tagged `hipcheck-v3.12.0`

chore: updated salsa to 0.18.0

---

hipcheck/src/cli.rs
hipcheck/src/main.rs

Relates to #674
This allows users to override the detected architecture when `hc ready` starts plugins.
Also, `hc ready` will now return `ExitCode::FAILURE` when any of its checks fail.
Feedback requested:

feat: Add `--arch` flag to `hc ready`, as used by `hc check`

---

Cargo.lock
plugins/binary/Cargo.toml
plugins/binary/plugin.kdl
plugins/binary/src/binary_detector.rs

Resolve issue #997  Removes the extraneous "." from the file extension string we extract from likely binary files in the binary plugin. The "." caused those file extension strings to fail to match with the known binary file extension strings we get from the default `Binary.kdl`.

fix: Binary plugin now correctly matches file extension strings

---

hipcheck/src/report/report_builder.rs
library/hipcheck-workspace-hack/Cargo.toml

Resolves Issue #994 Changes the explanation for a plugin with no default explanation from "no query explanation provided" to "output" to improve readability.

fix: Improves english message when missing default explanation

---

Cargo.lock
library/hipcheck-workspace-hack/Cargo.toml
sdk/python/LICENSE.md
sdk/python/pyproject.toml
xtask/Cargo.toml
xtask/src/build.rs
xtask/src/string.rs
xtask/src/task/validate.rs

Resolves issue #1008
`xtask validate` now validates both Rust crates and Python projects. For now, we manually include Hipcheck's only Python project in the list of code packages to examine.

feat(xtask): xtask validates Python projects

---

site/content/docs/getting-started/install.md

- added mold as dependency for building hipcheck for x86_64-unknown-linux-gnu
- added instructions for disabling mold
- fixed minor typo
Screenshot of updated docs:

docs: added mold-related instructions to install from source

---

site/content/docs/rfds/0011-lock-file-target.md

Resolves #962 .
(EDIT from Andrew: [Rendered](https://github.com/mitre/hipcheck/blob/5c1b5071741b538b19a3d2030abc01d1fe19eca7/site/content/docs/rfds/0011-lock-file-target.md))

feat: add RFD describing support for multi-repo target

---

site/templates/bases/base.tera.html
site/templates/index.html

This updates the tagline used on the site homepage to more clearly explain what Hipcheck does, and thereby imply why it's useful. This matches language that seemed to resonate with folks when I was discussing Hipcheck at the SoCal Linux Expo.

chore: Update tagline on site index

---

xtask/src/task/site/serve.rs

`cargo xtask site serve` now verifies the `tailwindcss` binary is version 3.x

chore: cargo xtask site serve verifies tailwindcss is v3.x

---

hipcheck/src/config.rs
hipcheck/src/policy/policy_file.rs

Closes #1000 
Tested with this `local.Hipcheck.kdl` policy file and all related files within `./config`
```
plugins {
plugin "mitre/activity" version="0.0.0" manifest="plugins/activity/local-plugin.kdl"
plugin "mitre/affiliation" version="0.0.0" manifest="plugins/affiliation/local-plugin.kdl"
plugin "mitre/binary" version="0.0.0" manifest="plugins/binary/local-plugin.kdl"
plugin "mitre/churn" version="0.0.0" manifest="plugins/churn/local-plugin.kdl"
plugin "mitre/entropy" version="0.0.0" manifest="plugins/entropy/local-plugin.kdl"
plugin "mitre/fuzz" version="0.0.0" manifest="plugins/fuzz/local-plugin.kdl"
plugin "mitre/review" version="0.0.0" manifest="plugins/review/local-plugin.kdl"
plugin "mitre/typo" version="0.0.0" manifest="plugins/typo/local-plugin.kdl"
}
patch {
plugin …
```

fix: allow analysis-only policies

---

hipcheck/src/cli.rs
site/content/docs/guide/cli/hc-check.md

When updating the documentation for #1009, I found `--ref <REFSPEC>` to be confusing. We are looking for a [git ref/reference](https://git-scm.com/book/en/v2/Git-Internals-Git-References) NOT a [git refspec](https://git-scm.com/book/en/v2/Git-Internals-The-Refspec)
Here is the new help menu:

chore: improve hc check --ref help

---

hipcheck/src/cli.rs
hipcheck/src/session/mod.rs
hipcheck/src/target/mod.rs
hipcheck/src/target/pm.rs
hipcheck/src/target/resolve.rs
hipcheck/src/target/types.rs

First pass at implementing the minimal amount of changes to support this function signature
```rust
impl TargetSeed {
pub fn get_targets(config: TargetResolverConfig) -> impl Iterator<Item = Target> {
...
```

refactor: TargetSeedKind refactor to support single and mulit targets

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/util/command.rs

Instead of merging #1051 , this removes the outdated `once_cell` crate in favor of the std library.

chore: replace once_cell::Lazy with std::LazyLock

---

plugins/activity/src/main.rs
plugins/affiliation/src/main.rs
plugins/churn/src/main.rs
plugins/entropy/src/main.rs
plugins/fuzz/src/main.rs
plugins/identity/src/main.rs
plugins/review/src/main.rs
plugins/typo/src/main.rs
sdk/rust/src/engine.rs
sdk/rust/src/lib.rs

Resolves #1064 
Moves trace level logs occurring in plugins to the shared functions in the query engine that they call.

chore: move plugin query trace log to engine.rs from plugins

---

hipcheck/src/policy/policy_file.rs
hipcheck/src/report/mod.rs
hipcheck/src/report/report_builder.rs
hipcheck/src/shell/mod.rs
sdk/rust/src/lib.rs
site/content/docs/rfds/0013-plugin-config-hash.md

Resolves #1058 .
Adds an additional field `reason` to `Recommendation` to identify why something is marked for investigation. When an "investigate-if-fail" policy is the cause of the overall "investigate" determination on a target, this now will display why in the output report, both in JSON and pretty-print form. Example below:
As an additional commit, fixed an issue with the SDK logger to make it print to stderr instead of stdout.

feat: investigate-if-fail in report

---

sdk/python/pyproject.toml
sdk/python/src/hipcheck_sdk/__init__.py
sdk/python/src/hipcheck_sdk/engine.py
sdk/python/src/hipcheck_sdk/options.py
sdk/python/src/hipcheck_sdk/server.py
sdk/python/tests/context.py
sdk/python/tests/example-plugin/local-plugin.kdl
sdk/python/tests/example-plugin/test_main.py
sdk/python/tests/test_mock_responses.py
sdk/python/uv.lock
site/content/docs/guide/making-plugins/python-sdk.md

- Removed the `mock_engine` SDK option, the `PluginEngine` now just checks if `mock_responses is not None` to decide whether to do mocked response.
- Added example query endpoint unit test to `main.py`, renamed `test_main.py` to make it easy for `pytest` to find
- Refactored `mock_responses` from a dict to a `list[tuple]`, because types we envision to be common query keys (object, dict, list) are not hashable by default. Now PluginEngine uses `find_response` function to get the right output object or return None.
- added default-True `init_logger` parameter to `PluginServer.register()` so people can init their own logger if they wish.
- Added section to Python SDK docs on website explaining how to write unit tests for query endpoint funcs

feat: python sdk unit testing capabilities

---

hipcheck/src/main.rs
hipcheck/src/report/mod.rs
hipcheck/src/report/report_builder.rs
hipcheck/src/score.rs
hipcheck/src/session/mod.rs
hipcheck/src/target/types.rs
sdk/schema/hipcheck_target_schema.json

Resolves #1068 . Refactors `Session` and supporting code for future implementation of running Hipcheck against multiple targets.
`Session` no longer contains a `Target` but instead has a `run()` function that takes a `Target` as an argument. When running against multiple `Target`s, we will initialize a base session with policy and configuration information, then clone that `Session` for each `Target` we want to call `session.run()`.
The current code for looping through `Target`s and `Report`s is only a placeholder that allows for unchanged runs against single targets but will be changed in future PRs.

feat: Refactor Session for support of multiple target runs

---

Cargo.lock
config/benchmark-targets.kdl
library/hipcheck-workspace-hack/Cargo.toml
xtask/Cargo.toml
xtask/src/main.rs
xtask/src/task/benchmark/linux/config.rs
xtask/src/task/benchmark/linux/mod.rs
xtask/src/task/benchmark/linux/results.rs
xtask/src/task/benchmark/mod.rs
xtask/src/task/manifest/mod.rs
xtask/src/task/mod.rs

This PR contains a first pass at implementing `cargo xtask benchmark`
I added a config file to the repository `./config/benchmark-targets.kdl` that contains three different repositories for benchmarking. I am very open to changing these repositories, but they serve as an example of how configuring benchmark gathering works! Each benchmark target currently requires a `ref` in order to make it easier to draw conclusions from benchmark run, as the targets should be constant across benchmark runs!
1. Ensure prerequisites are installed and `/proc/sys/kernel/perf_event_paranoid` (contains 2 or less)
2. Read config file and parse it to determine all benchmark targets
3. Build the release version of all binaries in the repo
4. Run `-r/--runs` number of benchmark runs for each benchmark targets …

feat: added first iteration of `cargo xtask benchmark`

---

hipcheck/src/target/mod.rs

Resolves #1101.
When urls that are prefaced with the `git://` protocol are indicated as targets, Hipcheck fetches the related the RemoteRepo over https.
Currently, it fails to recognize the target automatically and errors.

fix: parse git:// protocol target to recognize RemoteRepo

---

hipcheck/src/cli.rs
hipcheck/src/target/multi.rs
hipcheck/src/target/resolve.rs
hipcheck/src/target/tests/package-lock.json
hipcheck/src/target/types.rs

Related to #1071 .
Parses package-lock.json to SingleTargetSeeds. Called by `get_targets()` method of `TargetSeed`, currently just tested via a unit-test and a sample `package-lock.json` added in a test data folder. Will be used after CLI support for package-lock.json input is added.

feat: parse package-lock.json npm dependencies to SingleTargetSeeds

---

site/content/docs/contributing/pr-review.md

I edited the docs to include guidelines for PR submission since there's so many steps involved.

docs: editing documentation to include guidelines for pr submission

---

Cargo.lock
hipcheck/Cargo.toml
hipcheck/src/cli.rs
hipcheck/src/engine/mod.rs
hipcheck/src/main.rs
hipcheck/src/session/mod.rs
hipcheck/src/shell/mod.rs
hipcheck/src/target/resolve.rs
site/content/docs/getting-started/install.md

Resolves #1092 
Adds async code to analyze targets and print reports in parallel.
Adds `-j`/`--jobs` flag to `hc check` to allow users to set the number of parallel jobs.
Adds `summary` option to `-f`/`--format` flag that prints a one-line summary for each `Report`

feat: Add async target analysis

---

hipcheck/src/init/mod.rs
hipcheck/src/version.rs

Back when all analyses were bundled with Hipcheck core, we'd look for an npm binary at initialization because we'd need it to be able to do JavaScript analyses. Now, we won't need it, but we'd unintentionally retained it anyway. This commit removes the NPM checking.

fix: Stop checking NPM status at init.

---

Cargo.lock
hipcheck/Cargo.toml
library/hipcheck-common/Cargo.toml
library/hipcheck-macros/Cargo.toml
library/hipcheck-sdk-macros/Cargo.toml
plugins/activity/Cargo.toml
plugins/affiliation/Cargo.toml
plugins/binary/Cargo.toml
plugins/churn/Cargo.toml
plugins/entropy/Cargo.toml
plugins/fuzz/Cargo.toml
plugins/git/Cargo.toml
plugins/github/Cargo.toml
plugins/identity/Cargo.toml
plugins/linguist/Cargo.toml
plugins/npm/Cargo.toml
plugins/review/Cargo.toml
plugins/typo/Cargo.toml
sdk/rust/Cargo.toml

See https://github.com/mitre/hipcheck/issues/1149

chore: Bump versions to prep for 3.14.0 release.
